### ISSUE TITLE
How to add custom Data Annotator

### ISSUE THREAD

**Issue by joonhwan** [martinjw/dbschemareader#10]
Hi, I'm currently trying to generate poco classes for my NPoco based projects. 
Our DB ulgy namer. ie. MT_EQP_INFO for a table name, MT_EQP_ID for column name so far.
Removing 'MT_' part has been achieved with setting my customer ```INamer``` class instance to writer settings. Cool.
But unable to find any way to add some NPoco biased annotaion like following

```
[TableName("MT_EQP_INFO"), ...]
public partial class EqpInfo
{
  [ColumnName("MT_EQP_ID")]
  public EqpId { get; set;}
  // ...
}
```

How can I generate those attributed properties or classes using your nice tool?

Edited: I found DataAnnotaionWriter but it does not have any interface or injection mechanism. Any idea?

**Comment by martinjw** [comment]
I'll look at some extension points where you can hook into the code writing.

**Comment by martinjw** [comment]
Ok, how about this (strategy pattern).

```C#
            //inject the custom code inserter
            var codeWriterSettings = new CodeWriterSettings {CodeInserter = new CustomCodeInserter()};
            var cw = new CodeWriter(schema, codeWriterSettings);
```
CodeInserter is a base class, with 3 possible overrides. Here's one doing Entity Framework data annotations:

```C#
        public class CustomCodeInserter : CodeInserter
        {
            public override string WriteNamespaces(DatabaseTable table)
            {
                return "using System.ComponentModel.DataAnnotations.Schema";
            }

            public override string WriteTableAnnotations(DatabaseTable table)
            {
                return "[Table(\"" + table.Name + "\")]";
            }

            public override string WriteColumnAnnotations(DatabaseTable table, DatabaseColumn column)
            {
                return "[Column(\"" + column.Name + "\")]";
            }
        }
```

**Comment by joonhwan** [comment]
oh, That seems to be good enough.

**Comment by martinjw** [comment]
Pre-release now available https://github.com/martinjw/dbschemareader/releases/tag/1.6.0.3
Will push to nuget in a couple of days.

**Comment by joonhwan** [comment]
Oh, I checked and looks nice.

On the second thought, `CodeInserter`'s could have signature like this

```c#
public override void WriteTableAnnotations(DatabaseTable table, ClassWriter writer)
{
        writer.AppendLine("[Table(\"" + table.Name + "\")]");
        writer.AppendLine("[PrimaryKey(\"" + string.Joins(", ", table.PrimaryKey.Columns) + "\")]");
}
```
so that I can generate multiple lines of annotation with good indent.

**Comment by martinjw** [comment]
A new pre-release https://github.com/martinjw/dbschemareader/releases/tag/1.6.0.4
