### ISSUE TITLE
NetTypeForIntegers and boolean

### ISSUE THREAD

**Issue by dark2201** [martinjw/dbschemareader#100]
If column's type is tinyint it should be boolean but `NetDataType` returns `short`

https://github.com/martinjw/dbschemareader/blob/1bd333f72c5742950b183c367b38a7556def1a6d/DatabaseSchemaReader/DataSchema/DatabaseColumnExtensions.cs#L125

https://github.com/martinjw/dbschemareader/blob/1bd333f72c5742950b183c367b38a7556def1a6d/DatabaseSchemaReader/DataSchema/DatabaseColumnExtensions.cs#L137-L157

**Comment by martinjw** [comment]
In SqlServer I think bit is mostly used as a boolean. Value is 0, 1 or NULL.

Tinyint is a byte with values 0-255. It is commonly used to map state values and enums.  

This isn't the case for other databases. In MySql, booleans are mapped to tinyint(1) - and there's a synonym, "boolean" for it. In oracle you'd use NUMBER(1) with a check constraint (IN (0,1)). But there are also some terrifying databases that use CHAR(1).

I don't think we can automatically assume tinyints are booleans. In SqlServer, they are likely not to be, in other databases they may be booleans or they may be small numbers like enums. 

I think the NetTypeForIntegers method has to return int16/short as semantically that is correct- if the db designer used it for a more constrained type like boolean, that is easy to override in code before using it in code generation.
