### ISSUE TITLE
code gen error while using Oracle ODP.net provider.

### ISSUE THREAD

**Issue by sendreams** [martinjw/dbschemareader#102]
i have used the Oracle.ManagedDataAccess.Client.OracleConnection instead of System.Data.OracleClient.OracleConnection

`int idx = providerName.IndexOf("Oracle", StringComparison.OrdinalIgnoreCase);
            DatabaseReader rdr = null;
            if (idx > 0) {  // oracle
                var conn = new OracleConnection(connectionString);
                rdr = new DatabaseReader(conn);
            }`
it's ok and can process ReadAll().
then click 'code gen', click 'generate', will catch a exception in ResultSetReader.Execute().

**Comment by martinjw** [comment]
Do you have a stack trace from the exception?

I'm guessing it's something specific about your Oracle schema... If we can trace exactly what causes the error, it's probably a simple fix.

**Comment by moh-hassan** [comment]
I expect this issue is fixed using commit  [944f175](https://github.com/martinjw/dbschemareader/commit/944f175a07f70176def9303794cd780d4ff37161)
It's tested using `Oracle.ManagedDataAccess.Client v19.12.0`   and code generation is working fine.
