### ISSUE TITLE
Does not work with Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by tstaa** [martinjw/dbschemareader#103]
To reproduce:

1. create new .NET Core app (WPF in my case).
2. reference **Microsoft.Data.SqlClient** nuget package.
3. use the example for .NET Core.

**ReadAll** method returns empty, now if you reference **System.Data.SqlClient** nuget package instead, it works correctly.

According to Microsoft "[The Microsoft.Data.SqlClient package, now available in preview on NuGet, will be the flagship data access driver for SQL Server going forward.](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/)".

**Comment by martinjw** [comment]
Released in 2.7.2
