### ISSUE TITLE
Doesn't appear to respect default database when reading tables

### ISSUE THREAD

**Issue by samcov** [martinjw/dbschemareader#105]
In MySql(MariaDB), I have a connection string that specifies a default database. When I do something like this,

**var tableList = dr.TableList();**

I get the tables from every database in the instance, NOT just the tables in that particular default database.

I may be doing something wrong, but I don't know what it could be.

**Comment by martinjw** [comment]
The database in the connection string is just the initial database you connect to- the reader is using the information schema so it gets everything it can see. Just specify the database to the reader.
```C#
dr.Owner = "mydb";
var tableList = dr.TableList(); //now just tables in mydb
```

**Comment by samcov** [comment]
Great, thank you!

**Comment by samcov** [comment]
In case this can help someone else,

1. I specify the database in the connection string
2. I do this to eliminate specifying it in queries, i.e. database.tablename

In my database class, whenever I need to use your library, I do this(just showing mysql, but I do this for sql server, etc., as well,

if (database == null)
{
    MySqlConnectionStringBuilder conn = new MySqlConnectionStringBuilder(**this.connStr**);
    database = conn.Database;
}

Then I go on to get the table list or other information which limits it to the specified database in the connection string.

The important part is that the **MySqlConnectionStringBuilder** will parse the connection string for you and you can extract anything in there from it.
