### ISSUE TITLE
Doesn't seem to recognize Primary Key in table(MySql)

### ISSUE THREAD

**Issue by samcov** [martinjw/dbschemareader#106]
I have a table as shown in the picture and I get the DatabaseTable(DatabaseTable **OneTable**) then loop through the columns.

My test is to see if the column is the primary key so that I can set some properties, but it returns false for some reason for the **MessageID** column. Am I doing something wrong?

BTW, it detects that it's an identity column correctly, and knows that it's an auto number.

foreach (var column in **OneTable**.Columns)
  {
       var ispk = column.IsPrimaryKey;
       ..............................
  }
![image](https://user-images.githubusercontent.com/1551314/73592278-4e2fae00-44ad-11ea-8689-3e3c23822651.png)

**Comment by samcov** [comment]
**Correction**: I said MySql, however, I'm using MariaDB 10x

**Comment by martinjw** [comment]
Yes, column.IsPrimaryKey should work, unless for some reason it didn't find the primary key constraint for the table. The table should have a PrimaryKey property and a PrimaryKeyColumn which point to the same column. 

I tried with MariaDb 10.4 via MySql.Data.MySqlClient for a simple table just to confirm it was reading primary keys properly- it was ok.

**Comment by samcov** [comment]
Yes, I'm using the Oracle MySql Client as well, and as the picture shows, I have a primary key that is autonum. Here's the exported table. Not sure what's going on because this is not an issue with SqlServer with the identical table.

-- Dumping structure for table ivcbiz.avbmessages
CREATE TABLE IF NOT EXISTS `avbmessages` (
  `MessageID` int(11) NOT NULL AUTO_INCREMENT,
  `SenderID` int(11) NOT NULL COMMENT 'This is the user id of the sender',
  `ReplyID` int(11) NOT NULL DEFAULT -1,
  `SendToID` int(11) NOT NULL DEFAULT -1,
  `Email` varchar(128) NOT NULL,
  `Avtar` varchar(512) NOT NULL DEFAULT '',
  `Name` varchar(128) DEFAULT NULL,
  `Title` varchar(128) DEFAULT NULL,
  `Body` varchar(256) DEFAULT NULL,
  `RoleIds` varchar(512) DEFAULT NULL,
  `ToRoleIds` varchar(512) DEFAULT NULL,
  `ThreadID` int(11) DEFAULT NULL,
  `Created` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`MessageID`),
  KEY `FK_AvbMessages_AvbMessageThread` (`ThreadID`),
  CONSTRAINT `FK_AvbMessages_AvbMessageThread` FOREIGN KEY (`ThreadID`) REFERENCES `avbmessagethread` (`ThreadID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1244 DEFAULT CHARSET=latin1;

**Comment by samcov** [comment]
BTW, when I run the following: **SHOW KEYS FROM avbmessages WHERE Key_name = 'PRIMARY'**

I get,

![image](https://user-images.githubusercontent.com/1551314/73701975-1f2d5e00-46a0-11ea-9c89-d2d452818441.png)

**Comment by martinjw** [comment]
Just put your table into my test db, and it seems to read ok
![image](https://user-images.githubusercontent.com/2040281/73782863-0b165900-4793-11ea-92d2-fad2a6409a90.png)

**Comment by samcov** [comment]
Wow, I'll have to take a deeper dive into my code and see if I can detect what's wrong, I don't want to take up any more of your time until I get something more definitive.

**Comment by samcov** [comment]
FYI: I downloaded the source code a few days ago and it failed to load anything .net core in VS2019. **It failed saying it couldn't locate .net core sdk**.

I thought this was odd since I'm mostly doing .net core development. It took me a while, but then I looked at your global.json,

{
    "projects": [ "DatabaseSchemaReader", "CoreTest" ],
    "sdk": {
        "version": **"3.0.100"**
    }
}
I then ran "dotnet --list-sdks" and of course I don't have that version, it's removed when you move to .net 3.1 I guess., so I modified your global.json to the following and the projects load properly.

{
    "projects": [ "DatabaseSchemaReader", "CoreTest" ],
    "sdk": {
        "version": **"3.1.101"**
    }
}

**Comment by martinjw** [comment]
Yes, done for a slightly older sdk, before 3.1 was released. You can also delete the global.json so it takes the latest installed sdk. The sdk versioning on core has tripped me up a few times.

**Comment by samcov** [comment]
Ok, I now see the problem, but I'm not totally sure why it's happening.

1. If I use **var OneTable = dr.Table("avbmessages");**, because it's the only one I'm interested in, it says 
**IsPrimaryKey is FALSE**.

2. However, in the same using clause, if I use var tables = dr.AllTables(); and get all of the tables, then if I inspect the column, **IsPrimaryKey is TRUE**.

For some reason, it can't get it right if I'm looking for only one table.

**Comment by martinjw** [comment]
Both AllTables and Table use the same code- but with some differences.
The constraints are read using this: DatabaseSchemaReader/ProviderSchemaReaders/Databases/MySql/Constraints.cs https://github.com/martinjw/dbschemareader/blob/1612b7242f8989ce29f046fbb174a8738210eb33/DatabaseSchemaReader/ProviderSchemaReaders/Databases/MySql/Constraints.cs
The crucial difference is this WHERE statement is used with a specific tablename (line 51):

`WHERE     (keycolumns.table_name = @tableName OR @tableName IS NULL) AND `

Everything is linked through the INFORMATION_SCHEMA tables using the tablenames. For AllTables, it just gets everything, but I wonder if that query is going wrong for a specific table name - maybe another table with the same name in a different schema/database? 

Try to run the sql from that class directly with the tablename and see what it returns.

**Comment by samcov** [comment]
I ran this sql, and if I remove the order by it returns nothing, with the order by, it blows up with a sql error.

SELECT DISTINCT
cons.constraint_schema,
cons.constraint_name, 
keycolumns.table_name, 
column_name, 
ordinal_position, 
refs.unique_constraint_name, 
cons2.TABLE_SCHEMA AS fk_schema,
cons2.table_name AS fk_table,
refs.delete_rule AS delete_rule,
refs.update_rule AS update_rule
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS cons
    INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS keycolumns
        ON (cons.constraint_catalog = keycolumns.constraint_catalog
            OR cons.constraint_catalog IS NULL) AND
        cons.constraint_schema = keycolumns.constraint_schema AND
        cons.constraint_name = keycolumns.constraint_name AND
        cons.table_name = keycolumns.table_name
    LEFT OUTER JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS refs
        ON (cons.constraint_catalog = refs.constraint_catalog
            OR cons.constraint_catalog IS NULL) AND
        cons.constraint_schema = refs.constraint_schema AND
        cons.constraint_name = refs.constraint_name AND
        cons.table_name = refs.table_name
    LEFT OUTER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS cons2
        ON (cons2.constraint_catalog = refs.constraint_catalog
            OR cons2.constraint_catalog IS NULL) AND
        cons2.constraint_schema = refs.constraint_schema AND
        -- MySQL 8.0.12 bug https://bugs.mysql.com/bug.php?id=90690 requires collate clause
        cons2.constraint_name COLLATE utf8_unicode_ci = refs.unique_constraint_name COLLATE utf8_unicode_ci AND
        cons2.table_name = refs.referenced_table_name
WHERE 
    (keycolumns.table_name = 'avbmessages') AND 
    (cons.constraint_schema = 'ivcbiz') AND 
    cons.constraint_type = @constraint_type
ORDER BY
    cons.constraint_schema, keycolumns.table_name, cons.constraint_name, ordinal_position";

**Comment by martinjw** [comment]
This works on my db
```sql
SELECT DISTINCT
cons.constraint_schema,
cons.constraint_name, 
keycolumns.table_name, 
column_name, 
ordinal_position, 
refs.unique_constraint_name, 
cons2.TABLE_SCHEMA AS fk_schema,
cons2.table_name AS fk_table,
refs.delete_rule AS delete_rule,
refs.update_rule AS update_rule
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS cons
    INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS keycolumns
        ON (cons.constraint_catalog = keycolumns.constraint_catalog
            OR cons.constraint_catalog IS NULL) AND
        cons.constraint_schema = keycolumns.constraint_schema AND
        cons.constraint_name = keycolumns.constraint_name AND
        cons.table_name = keycolumns.table_name
    LEFT OUTER JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS refs
        ON (cons.constraint_catalog = refs.constraint_catalog
            OR cons.constraint_catalog IS NULL) AND
        cons.constraint_schema = refs.constraint_schema AND
        cons.constraint_name = refs.constraint_name AND
        cons.table_name = refs.table_name
    LEFT OUTER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS cons2
        ON (cons2.constraint_catalog = refs.constraint_catalog
            OR cons2.constraint_catalog IS NULL) AND
        cons2.constraint_schema = refs.constraint_schema AND
        -- MySQL 8.0.12 bug https://bugs.mysql.com/bug.php?id=90690 requires collate clause
        cons2.constraint_name COLLATE utf8_unicode_ci = refs.unique_constraint_name COLLATE utf8_unicode_ci AND
        cons2.table_name = refs.referenced_table_name
WHERE 
(keycolumns.table_name = 'avbmessages' OR 'avbmessages' IS NULL) AND
 (cons.constraint_schema = 'gtest' OR 'gtest' IS NULL) AND 
    cons.constraint_type = 'PRIMARY KEY'
ORDER BY
    cons.constraint_schema, keycolumns.table_name, cons.constraint_name, ordinal_position
```
(Schema name varies, but that's the parameters it will be using)

**Comment by samcov** [comment]
For now I have a fix, I'll just get all tables and loop through until I find the one of interest and use it. That works every time.

**Comment by samcov** [comment]
I must have had something missing, I modified yours and it works!

`SELECT DISTINCT
cons.constraint_schema,
cons.constraint_name, 
keycolumns.table_name, 
column_name, 
ordinal_position, 
refs.unique_constraint_name, 
cons2.TABLE_SCHEMA AS fk_schema,
cons2.table_name AS fk_table,
refs.delete_rule AS delete_rule,
refs.update_rule AS update_rule
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS cons
    INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS keycolumns
        ON (cons.constraint_catalog = keycolumns.constraint_catalog
            OR cons.constraint_catalog IS NULL) AND
        cons.constraint_schema = keycolumns.constraint_schema AND
        cons.constraint_name = keycolumns.constraint_name AND
        cons.table_name = keycolumns.table_name
    LEFT OUTER JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS refs
        ON (cons.constraint_catalog = refs.constraint_catalog
            OR cons.constraint_catalog IS NULL) AND
        cons.constraint_schema = refs.constraint_schema AND
        cons.constraint_name = refs.constraint_name AND
        cons.table_name = refs.table_name
    LEFT OUTER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS cons2
        ON (cons2.constraint_catalog = refs.constraint_catalog
            OR cons2.constraint_catalog IS NULL) AND
        cons2.constraint_schema = refs.constraint_schema AND
        -- MySQL 8.0.12 bug https://bugs.mysql.com/bug.php?id=90690 requires collate clause
        cons2.constraint_name COLLATE utf8_unicode_ci = refs.unique_constraint_name COLLATE utf8_unicode_ci AND
        cons2.table_name = refs.referenced_table_name
WHERE 
(keycolumns.table_name = 'avbmessages' OR 'avbmessages' IS NULL) AND
 (cons.constraint_schema = 'ivcbiz' OR 'ivcbiz' IS NULL) AND 
    cons.constraint_type = 'PRIMARY KEY'
ORDER BY
    cons.constraint_schema, keycolumns.table_name, cons.constraint_name, ordinal_position`

**Comment by samcov** [comment]
![image](https://user-images.githubusercontent.com/1551314/73882742-7efa4500-4817-11ea-8262-6133e95a71cf.png)
