### ISSUE TITLE
Bad Naming conventions

### ISSUE THREAD

**Issue by proazr** [martinjw/dbschemareader#107]
Just started using this for one of my projects, and it works well. Thank you for your time and effort, 

Having said that, I noticed some poor naming conventions used. It would be nice if the methods were not named to be nouns. Here's an example from the DatabaseSchemaReader/DatabaseReader.cs :

![image](https://user-images.githubusercontent.com/51807907/73600730-6988d080-4522-11ea-8294-dc989b90537d.png)

Regards.

**Comment by martinjw** [comment]
Yes, there are a few names were are not quite ideal. It's a breaking change to rename them now, but if there are some significant rewrites to the project I'll try to rationalize the names.
