### ISSUE TITLE
MySql Json native type support

### ISSUE THREAD

**Issue by safepage** [martinjw/dbschemareader#110]
Hi,

I'd like to add support for the native MySql Json data type into the DataTypeList (mapped to "System.String") but I'm not sure what ProviderDbType should be?

Thanks

**Comment by martinjw** [comment]
It should be the integer value of the provider DbType enum 

For MySql it's MySql.Data.MySqlClient.MySqlDbType, and the value for JSON is 245

It's used in mapping parameter types - specifically MySqlParameter.MySqlDbType .

**Comment by safepage** [comment]
This worked thanks.
