### ISSUE TITLE
sqlite primarykey has multi columns

### ISSUE THREAD

**Issue by zls3201** [martinjw/dbschemareader#118]
database script
```
CREATE TABLE "post_tag_map" (
    "post_id" varchar(50) NOT NULL,
    "tag_id" varchar(50) NOT NULL,
    CONSTRAINT "PK_post_tag_map" PRIMARY KEY ("tag_id", "post_id"),
);
```
execute sql 
```
PRAGMA table_info('post_tag_map')
```
![image](https://user-images.githubusercontent.com/1707458/111565122-ce11f800-87d5-11eb-9e63-4e77fbe9ce3d.png)

[\DatabaseSchemaReader\ProviderSchemaReaders\Databases\SQLite\Constraints.cs](https://github.com/martinjw/dbschemareader/blob/master/DatabaseSchemaReader/ProviderSchemaReaders/Databases/SQLite/Constraints.cs)
Line: 98

modify
"bool isPrimaryKey = dr.GetBoolean("pk");" to 
"bool isPrimaryKey = dr.GetInt("pk") > 0;"

![image](https://user-images.githubusercontent.com/1707458/111565587-96f01680-87d6-11eb-953c-db92982c8de0.png)

**Comment by martinjw** [comment]
Thanks- source updated. Nuget will be updated tomorrow.
