### ISSUE TITLE
MigrationGenerator does not generate correct oracle data type for int64.

### ISSUE THREAD

**Issue by rufio620** [martinjw/dbschemareader#12]
The oracle migration generator does not appear to map long integer data types (Int64) correctly. In the example below an Int64 is being mapped to non existent oracle type bigint. It should be NUMBER(19) according to http://docs.oracle.com/cd/B19306_01/gateways.102/b14270/apa.htm 

``` c#
var newTable = new DatabaseTable { Name = "TestTable" };

var idColumn = newTable.AddColumn("Id", DbType.Int64);
idColumn.AddPrimaryKey("PK_TestTable");
//idColumn.DefaultValue = $"next value for {pkSeqName}";

var summaryColumn = newTable.AddColumn("Summary", DbType.String);
summaryColumn.Length = 100;

gen.AddTable(newTable)
```

--script output
CREATE TABLE "TestTable"
(
  "Id" BIGINT NOT NULL,
  "Summary" NVARCHAR2 (100) NOT NULL
);
ALTER TABLE "TestTable" ADD CONSTRAINT "PK_TestTable" PRIMARY KEY ("Id");

**Comment by martinjw** [comment]
Creating a table using the fluent extensions (AddColumn) automatically translates types/DbTypes into SqlServer types.

You can fix this by making sure the table is part of a DatabaseSchema with a provider type of Oracle. Like this:
```C#
var schema = new DatabaseSchema(null, SqlType.SqlServer);
var newTable = schema.AddTable("TestTable");
```

This will give you NUMBER (15). So I pushed a commit which uses NUMBER (19). It will automatically translate the SqlServer BigInt into the correct Oracle type, so your original code sample will work as well.
