### ISSUE TITLE
.NET core 6

### ISSUE THREAD

**Issue by fasteddys** [martinjw/dbschemareader#128]
Hello can you please update to core 6.0 framework

**Comment by martinjw** [comment]
You can use it from .net 6 already - nuget will use the netstandard target, which works great. 

If you use the DatabaseSchemaViewer.exe from the releases, it is net4.x/WindowsForms- I could now update it for net6, although perhaps Maui or some other UI would be better?

**Comment by fasteddys** [comment]
which ever works is fine. thanks
