### ISSUE TITLE
[Suggestion] Add a ViewExists method

### ISSUE THREAD

**Issue by iulian0512** [martinjw/dbschemareader#130]

**Comment by martinjw** [comment]
How would this be different to `schemaReader.Views.Any(v => v.Name == `"X")` ?

**Comment by iulian0512** [comment]
your example loads all the views in app memory then loops all until a match is found, whereas viewexists could be a query sent to the db 'select * from info_schema where view_name='myview''

**Comment by martinjw** [comment]
reader.ViewExists(name) released in 2.7.12
