### ISSUE TITLE
use “DatabaseReader.Table(tableName)” bug?

### ISSUE THREAD

**Issue by cm0201** [martinjw/dbschemareader#133]
ver：2.7.12

use 'DatabaseReader.Table(tableName)'
table.Columns DataType is null。

use 'DatabaseReader.AllTable()' no problem

![image](https://user-images.githubusercontent.com/6092940/186050850-1d8eb5e8-ca3a-47cf-948b-628a3c027769.jpg)

**Comment by cm0201** [comment]
temporary solution：
![solution](https://user-images.githubusercontent.com/6092940/186091779-32296d83-3533-4ba3-b246-9a8e5eddd274.png)

**Comment by martinjw** [comment]
Candidate release for this https://github.com/martinjw/dbschemareader/releases/tag/2.7.13.0

**Comment by martinjw** [comment]
Fixed in https://github.com/martinjw/dbschemareader/releases/tag/2.7.13.3
