### ISSUE TITLE
PostgreSQL: Alter column does not take default values into account

### ISSUE THREAD

**Issue by Arnagos** [martinjw/dbschemareader#135]
Altering columns in a PostgreSQL database does not take default values into account.
I think this is because the [PostgreSqlMigrationGenerator](https://github.com/martinjw/dbschemareader/blob/master/DatabaseSchemaReader/SqlGen/PostgreSql/PostgreSqlMigrationGenerator.cs) `AlterColumn` method doesn't contain code to handle this.

**Comment by martinjw** [comment]
There are potential issues with default values and changed types with USING (in #132) where PostgreSql recommends dropping the default, altering the type, then doing a set default. All of which is a bit complicated and maybe overkill for the types of alter column people actually do?

**Comment by martinjw** [comment]
Candidate release for this https://github.com/martinjw/dbschemareader/releases/tag/2.7.13.0
