### ISSUE TITLE
DropTable only takes the ForeignKeyChildren into account and ignores the ForeignKeys of the table itself

### ISSUE THREAD

**Issue by Arnagos** [martinjw/dbschemareader#136]
DropTable only considers the ForeignKeyChildren and ignores the ForeignKeys of the table itself. This means that it does drop the foreign key constraints set on other tables but not the ones on the dropped table itself.

A table like this:
![image](https://user-images.githubusercontent.com/21961872/186895839-db4a29ea-c55b-41ff-b5e5-74c4aff38994.png)

Results in this SQL: `DROP TABLE [dbo].[Testing__BaseTypesAllTypes];`

**Comment by martinjw** [comment]
Not sure I understand this...
In most (all?) databases, DROP TABLE will also drop all the contraints on the table itself. It's the dependencies (foreign key children) that we must worry about.

Here's a simple schema
* Customers table
* Orders table, has fk to Customers

What happens?
* If I drop Orders, the fk to customers is automatically dropped, but the customers table remains
* If I drop Customers I have to drop the fk constraint on Orders first OR do a CASCADE for the database to do it

**Comment by Arnagos** [comment]
I'm very sorry, you're correct. It seems I had a bug in my code that I didn't notice.
