### ISSUE TITLE
MigrationGenerator.DropColumn does not take unique index (maybe all indices?) into account

### ISSUE THREAD

**Issue by Arnagos** [martinjw/dbschemareader#139]
First: Thanks for your work fixing all of these issues!

Dropping a unique foreign key column in MSSQL results in an SQL exception.

Column:
![image](https://user-images.githubusercontent.com/21961872/187438679-23ce6357-784d-4b59-8bab-424560c3ae73.png)

Index:
![image](https://user-images.githubusercontent.com/21961872/187439883-3408fbbc-014c-47de-a649-c9d0bc427a8b.png)

Generated SQL:
```
ALTER TABLE [dbo].[Punchclock__Company] DROP CONSTRAINT [Punchclock__Company_Own_Contact]
ALTER TABLE [dbo].[Punchclock__Company] DROP COLUMN [ContactInfoId];
```

Exception:
```
The index 'Punchclock__Company_ContactInfoId_idx' is dependent on column 'ContactInfoId'.
ALTER TABLE DROP COLUMN ContactInfoId failed because one or more objects access this column.
```

**Comment by Arnagos** [comment]
I created a local NuGet package and tried it out. Works perfectly fine.

**Comment by Arnagos** [comment]
Aah, I was wrong. There is a bug in this. The new code does not remove the constraints / indices that it dropped from the schema / table and generates SQL like this:
```
DROP INDEX [Punchclock__Company_ContactInfoId_idx] ON [dbo].[Punchclock__Company];
ALTER TABLE [dbo].[Punchclock__Company] DROP CONSTRAINT [Punchclock__Company_Own_Contact]
ALTER TABLE [dbo].[Punchclock__Company] DROP COLUMN [ContactInfoId];

ALTER TABLE [dbo].[Punchclock__Company] DROP CONSTRAINT [Punchclock__Company_Own_Contact];
DROP INDEX [Punchclock__Company_ContactInfoId_idx] ON [dbo].[Punchclock__Company];
```

**Comment by martinjw** [comment]
The order of operations in CompareSchemas for dropping columns is the opposite to adding columns, so this is problematic - but at least for sqlServer, IF EXISTS neatly avoids an error. Fortunately dropping columns is rare- esp if they have indexes/constraints - tables tend to grow, not shrink. In years of use of this, I've never found this bug before !

**Comment by Arnagos** [comment]
Do you have an ETA for a new release on NuGet?

**Comment by martinjw** [comment]
https://www.nuget.org/packages/DatabaseSchemaReader/ Just released!

**Comment by Arnagos** [comment]
Are you sure that you released the correct version? DatabaseIndex does not contain the Filter property in this release.

**Comment by martinjw** [comment]
I had a small technical update anyway, so there's a new nuget package now.
