### ISSUE TITLE
Feature Request: Option to create a nullable unique index

### ISSUE THREAD

**Issue by Arnagos** [martinjw/dbschemareader#140]
I can't seem to find an option to create nullable unique indices.

I think it would be reasonable to create a nullable unique index whenever any column(s) of the index can be null.

Desired SQL:
```
CREATE UNIQUE NONCLUSTERED INDEX [Punchclock__Company_ContactInfoId_idx] 
    ON [Punchclock__Company]([ContactInfoId])
    WHERE [ContactInfoId] IS NOT NULL;
```

Currently, it just generates this SQL:
```
CREATE UNIQUE NONCLUSTERED INDEX [Punchclock__Company_ContactInfoId_idx] 
    ON [Punchclock__Company]([ContactInfoId]);
```

**Comment by Arnagos** [comment]
Sure, generating this much myself should be no problem at all. Thanks!

**Comment by Arnagos** [comment]
I created a local NuGet package and tried it out. Works perfectly fine.

**Comment by Arnagos** [comment]
Are you sure that you released the correct version? `DatabaseIndex` does not contain the `Filter` property in this release.

**Comment by Arnagos** [comment]
@martinjw Can you also add this feature to PostgreSQL? It's supported via [partial indexes](https://www.postgresql.org/docs/current/indexes-partial.html). The syntax seems to be the exact same as in MSSQL.

**Comment by Arnagos** [comment]
Sadly the change generates invalid SQL:
```
CREATE INDEX "X_idx" ON "Y"("A", "B", "C"); WHERE "C" IS NOT NULL
```

The `;` is not removed from the end of the initial SQL and also not appended to the new ending.

**Comment by martinjw** [comment]
Fixed in https://github.com/martinjw/dbschemareader/releases/tag/2.10.1.0
