### ISSUE TITLE
from DatabaseColumn.DataType, can't get unsigned/signed for int to from DatabaseColumn.DataType, can't get unsigned/signed info for int

### ISSUE THREAD

**Issue by yajiya** [martinjw/dbschemareader#15]
1. No signed/unsigned info for DataType
DbDataType: "mediumint(9) unsigned"

DataType:
{MEDIUMINT = System.Int32}
    CreateFormat: "MEDIUMINT"
    IsDateTime: false
    IsFloat: false
    IsInt: true
    IsNumeric: true
    IsString: false
    IsStringClob: false
    LiteralPrefix: null
    LiteralSuffix: null
    NetDataType: "System.Int32"
    NetDataTypeCSharpName: "int"
    ProviderDbType: 9
    TypeName: "MEDIUMINT"

**Comment by martinjw** [comment]
The signed/unsigned information isn't held in column.DataType, it's only kept in column.DbDataType (the string form of what we get from the database metadata).

There is an extension method, column.DataTypeDefinition(), which returns the type as a string suitable for DDL. This preserves the signed/unsigned flag. Most parts of the DatabaseSchemaReader that write SQL use this extension. The information isn't lost.

To get a simple boolean flag, you'd have to do a column.DbDataType.IndexOf("unsigned") != -1.
