### ISSUE TITLE
Console.Writeline in ResultSetReader.Execute method

### ISSUE THREAD

**Issue by whibdev** [martinjw/dbschemareader#154]
In last update there was a Console.Writeline introduced that prints the datatype full name.
`Console.WriteLine(column.DataType.FullName);`
See line 198 of /DatabaseSchemaReader/Procedures/ResultSetReader.cs
![2022-11-24_10-07-06](https://user-images.githubusercontent.com/4193683/203845894-95c0238b-f5a1-4b18-8fdb-cd97e3a819e1.png)

**Comment by martinjw** [comment]
Oops. Removed now

**Comment by whibdev** [comment]
Do you have a timeline on when this will be published?

**Comment by martinjw** [comment]
> Do you have a timeline on when this will be published?

Will be in 2.8.0, which should be published in the next week

**Comment by martinjw** [comment]
https://github.com/martinjw/dbschemareader/releases/tag/2.8.0.0
