### ISSUE TITLE
PostgreSQL table script generator, incorrect default text value

### ISSUE THREAD

**Issue by r-work** [martinjw/dbschemareader#157]
It seems to add an extra single quote at the end which causes syntax error, like the following example (note the single quote after the `text` type):

```SQL
CREATE TABLE public.global_settings
(
  id BIGINT NOT NULL,
  time_format TEXT  DEFAULT 'HH:mm'::text'
)
```

**Comment by martinjw** [comment]
https://github.com/martinjw/dbschemareader/releases/tag/2.8.0.0
