### ISSUE TITLE
Will support sqlserver high version?

### ISSUE THREAD

**Issue by Cricle** [martinjw/dbschemareader#159]
https://github.com/martinjw/dbschemareader/blob/a31e05d171cbd79ca0db05ec2247b10b68dd5438/DatabaseSchemaReader/DataSchema/SqlType.cs#L7-L12

In sqlserver2019 execute `AllTables` got nothing.

**Comment by martinjw** [comment]
I'm using sql server 2019 developer edition myself. Is there an error? Are you sure the connection string is good?

**Comment by Cricle** [comment]
The query result schema will be const `dbo`.
```sql
SELECT @@VERSION
-- Microsoft SQL Server 2017 (RTM-GDR) (KB5021127) - 14.0.2047.8 (X64) 
--	Jan 25 2023 08:29:55 
--	Copyright (C) 2017 Microsoft Corporation
--	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19045: ) (Hypervisor)

```

**Comment by Cricle** [comment]
I think it had been support in current version.
I forked the project, and self design to support what I used version.

Very thanks the project and author.

Now I closed the issuer.
