### ISSUE TITLE
Comparison Options

### ISSUE THREAD

**Issue by ronnyek** [martinjw/dbschemareader#16]
Would you guys be interested in a pull request with a bit more in the implementation of some comparison options? Eg, I'd like to be able to filter out database implementation specifics. Comparing a postgres database to a sql server one, I'm getting a lot of comparisons with differeing owners, or pgsql returning a ton of information_schema and pg_catalog entries. I was able to manually filter those differences pretty easily... however another change its suggesting is dropping a table and recreating because public owner vs dbo. 

I'd be more than happy to investigate the changes, and if I have luck... I'll submit a pull request for it.

**Comment by martinjw** [comment]
@ronnyek  Yes, sure - pull requests welcome! 

There are 2 existing ways to not have information_schema etc :  either specify the databaseReader.Owner and/or use databaseReader.Exclusions. Set those before reading, and it'll read faster too.
