### ISSUE TITLE
SqlServerMigrationGenerator.FindDefaultConstraint uses the new column name to drop constraints of the old column

### ISSUE THREAD

**Issue by Arnagos** [martinjw/dbschemareader#166]
[SqlServerMigrationGenerator.FindDefaultConstraint](https://github.com/martinjw/dbschemareader/blob/4f4769c8a62e726398f96581b04297ae3a659005/DatabaseSchemaReader/SqlGen/SqlServer/SqlServerMigrationGenerator.cs#L32C77-L32C77) uses the new column name to drop constraints of the old column. This prevents the application form finding the existing default constraint when both the default value and the name of the column have changed at the same time.

Old column:
![image](https://github.com/martinjw/dbschemareader/assets/21961872/808b9447-78ca-4bd0-a6a3-3633b086b339)

New column:
![image](https://github.com/martinjw/dbschemareader/assets/21961872/5b88e7d2-a7f7-4468-9537-f9f1ad15b2c7)

Result: Existing default value not found; new one gets created anyway -> `System.Data.SqlClient.SqlException (0x80131904): Column already has a DEFAULT bound to it.`

**Comment by martinjw** [comment]
Fixed in https://github.com/martinjw/dbschemareader/releases/tag/2.8.2.1 I hope
Will push to nuget later

**Comment by martinjw** [comment]
Now released to nuget
