### ISSUE TITLE
Script User Defined Types

### ISSUE THREAD

**Issue by whibdev** [martinjw/dbschemareader#171]
I'm able to see properties of UserDefinedTables and UserDataTypes, but I haven't been able to find methods to generate creation scripts; is this available?

**Comment by martinjw** [comment]
You need the migrationGenerator. But I'll add an extension method which does this to types and tables
```c#
            var ddlGeneratorFactory = new DdlGeneratorFactory(sqlType);
            var migrationGenerator = ddlGeneratorFactory.MigrationGenerator();
            return migrationGenerator.AddUserDataType(udt);
```

**Comment by martinjw** [comment]
In 2.9.1
