### ISSUE TITLE
Duplicating of MSSQL User Data Types 

### ISSUE THREAD

**Issue by icansiz** [martinjw/dbschemareader#173]
Hi,

The criteria in the query below should be as follows
**_st2.name <> 'sysname'_**

<img width="627" alt="image" src="https://github.com/martinjw/dbschemareader/assets/34852195/e8a82f51-cf56-47ef-bb26-0c5faa8f3a2c">

**Comment by icansiz** [comment]
Source file name: DatabaseSchemaReader/ProviderSchemaReaders/Databases/SqlServer/UserDataTypes.cs

**Comment by martinjw** [comment]
Fixed in https://github.com/martinjw/dbschemareader/releases/tag/2.10.1.0
