### ISSUE TITLE
Question: How to add IF EXISTS to generated DDL

### ISSUE THREAD

**Issue by swidz** [martinjw/dbschemareader#179]
Hi,

Is it possible to generate DLL with "IF EXISTS" condition?

e.g. 
https://www.sqlite.org/lang_droptable.html 
DROP TABLE IF EXISTS myTable;

Regards,
Sebastian

**Comment by martinjw** [comment]
Fixed in https://github.com/martinjw/dbschemareader/releases/tag/2.11.0.0
