### ISSUE TITLE
c# code gen does not compile.

### ISSUE THREAD

**Issue by Charles113** [martinjw/dbschemareader#180]
Hey,

Code gen c#, found 2 bugs.
Generated code does not compile.

Bug: Buchungsherkunft and VorgangsArt exist in both ErloesKontoPosition and KontoPosition
Name should be changed if the collection name already exists?

	

--------------

	/// <summary>
	/// Class representing VorgangsArt table
	/// </summary>
	public class VorgangsArt
	{

	  public VorgangsArt()
	  {
		  // Bug: Duplicate names if property exist in two tables
		  BuchungsherkunftCollection = new List<ErloesKontoPosition>();
		  VorgangsArtCollection = new List<ErloesKontoPosition>();
		  BuchungsherkunftCollection = new List<KontoPosition>();
		  VorgangsArtCollection = new List<KontoPosition>();
	  }
	  
	  [Key]
	  public int Id { get; set; }

	  [Required]
	  [StringLength(100)]
	  public string Name { get; set; }

	  [Required]
	  public int Kennzahl { get; set; }

	  public virtual ICollection<ErloesKontoPosition> BuchungsherkunftCollection { get; private set; }

	  public virtual ICollection<ErloesKontoPosition> VorgangsArtCollection { get; private set; }

	  public virtual ICollection<KontoPosition> BuchungsherkunftCollection { get; private set; }

	  public virtual ICollection<KontoPosition> VorgangsArtCollection { get; private set; }

	  // Bug: Buchungsherkunft and VorgangsArt exist in both ErloesKontoPosition and KontoPosition
	  // Name should be changed?

    // table ErloesKontoPosition
	  // public virtual VorgangsArt Buchungsherkunft { get; set; }
	  // public virtual VorgangsArt VorgangsArt { get; set; }

    // table KontoPosition
	  // public virtual VorgangsArt Buchungsherkunft { get; set; }
	  // public virtual VorgangsArt VorgangsArt { get; set; }

	}
	
-------------

Then in another table it generates the following property:

	Why put a range?
	Menge can be negative.
	
	[Required]
	[Range(typeof(decimal), "0", "999999999999999")]
	public decimal Menge { get; set; }

**Comment by martinjw** [comment]
There is a pre-release here: https://github.com/martinjw/dbschemareader/releases/tag/2.10.1.10

Annotation ranges - For integers I'm keeping the range lower bound as 0 - most domain models will prefer this. But for decimals, yes, it should allow negative numbers (we don't attempt to parse check constraints).

For foreign key collections- I've changed the default rule to use table+column so it should be unique, but please check

**Comment by martinjw** [comment]
Fixed in https://github.com/martinjw/dbschemareader/releases/tag/2.11.0.0
