### ISSUE TITLE
POCO column name error when column is both primary and foreign key

### ISSUE THREAD

**Issue by MachineCognitis** [martinjw/dbschemareader#21]
I am using the code generator to create POCO classes for my database schema. I have a Department table with a composite primary key BusinessUnitId + DepartmentId, The BusinessUnitId is also a foreign key to the BusinessUnit table. When the POCO class for Department is created, the Id suffix is stripped from BusinessUnitId (by the Namer.Name() function) and this creates two members with the same name (BusinessUnit) in the Department class. I guess the Id should not be removed when a column is also a primary key. What do you think?

**Comment by martinjw** [comment]
There's a fix: set the CodeWriterSettings.UseForeignKeyIdProperties = true

This writes 2 properties- the scalar "Id" property (BusinessUnitId), and the instance reference (BusinessUnit)

**Comment by MachineCognitis** [comment]
I set the property as you said but that did not change anything. When I comment the following line of the `Namer.Name(),` then I get the correct property name,

 ` //name = name.Substring(0, name.Length - 2);`

**Comment by MachineCognitis** [comment]
Thanks, I will test when you release a new NuGet package.

**Comment by martinjw** [comment]
I've written a test to investigate this - the linked commit should appear here. The Arrange method creates the schema with the in-memory syntax, which should match your description. 

This test produces the right results for me- so I must have some details wrong.

Here's what I get (with CodeWriterSettings CodeTarget=Poco).
It creates a "Key" class, which is the composite key with scalar values. This is the best way to model it for most ORMs.  
```c#
    public class Department
    {
        public virtual DepartmentKey Key { get; set; }

        public virtual BusinessUnit BusinessUnit { get; set; }

    }

    /// <summary>
    /// Class representing Department composite key
    /// </summary>
    public class DepartmentKey
    {
        public virtual int DepartmentId { get; set; }

        public virtual int BusinessUnitId { get; set; }

        #region overrides

        public override string ToString()
        {
            return "[DepartmentId] = " + DepartmentId + " [BusinessUnitId] = " + BusinessUnitId;
        }
```
If you use Entity Framework (CodeTarget.PocoEntityCodeFirst), it doesn't need the key class, so it looks like this:
```c#
    public class Department
    {
        [Display(Name="Department Id")]
        [Key]
        public int DepartmentId { get; set; }

        [Display(Name="Business Unit")]
        [Key]
        public int BusinessUnitId { get; set; }

        public virtual BusinessUnit BusinessUnit { get; set; }
    } 
```

**Comment by MachineCognitis** [comment]
Here is a zip file that contains the Oracle definition of the BusinessUnits and Departments tables, the test VB.NET Module1.vb program, and the CodeWriter output folder. The Departments.cs is the problematic class since it has two members with the name BusinessUnit.

[Test.zip](https://github.com/martinjw/dbschemareader/files/622095/Test.zip)

Thanks.

**Comment by martinjw** [comment]
Got a repo- something to do with BusinessUnitId being both a primary key and 2 different foreign keys. Now to fix it...

**Comment by MachineCognitis** [comment]
Hi,

The issue still exists. I have attached the CodeWriter output folder and the definition of related Oracle tables. The problematic classes are Period, Season, and Site. If you need more detailed info, let me know.

[Test.zip](https://github.com/martinjw/dbschemareader/files/649346/Test.zip)

Thanks.

**Comment by martinjw** [comment]
More issues around naming composite primary keys which are also foreign keys. 

There's a pre-release at https://github.com/martinjw/dbschemareader/releases/tag/2.2.0.9

It's possible there are other naming collisions, but this fixes the issues for the tables you supplied.

**Comment by MachineCognitis** [comment]
Yes, it is working. Thanks!
