### ISSUE TITLE
Suggestion: add option to reverse Filter exclusion logic to inclusion

### ISSUE THREAD

**Issue by MachineCognitis** [martinjw/dbschemareader#22]
I was wondering whether it would be possible to add a bool option to the Filter class to reverse the exclude logic; this would effectively gives us an inclusion filter rather than an exclusion filter. A client would be able to select for each of the 4 Exclusions filters, whether to use exclusion or exclusion. The default would be exclusion. What do you think?

By the way, this is a great package!

**Comment by martinjw** [comment]
The method is "Exclude", so inverting it may be a little confusing. 

I'd rather keep the standard Filter logic straightforward, and add a custom, explicit inversion:
```C#
    public class InclusionFilter : Filter
    {
        public override bool Exclude(string name)
        {
            //inverted, so exclusion is really inclusion
            if (!FilterExclusions.Contains(name)) return true;
            return false;
        }
    }
```

**Comment by MachineCognitis** [comment]
Good point, let me know when this new feature is available!
