### ISSUE TITLE
More support for DB-specific schema information; especially SQL Server

### ISSUE THREAD

**Issue by hmmueller** [martinjw/dbschemareader#23]
I have forked your nice project because we might replace a Redgate SchemaCompare with it (for various reasons). However, for this, we need quite a few more attributes for SQL-Server specific Information.

What I do right now in my fork:
- I have written a (IMHO) simpler comparer, which OTOH can filter out arbitrary objects based on names; see here for the first rough implementation: [DatabaseSchemaComparer.txt](https://github.com/martinjw/dbschemareader/files/619198/DatabaseSchemaComparer.txt)
- I have added a class DatabaseStatistics for SQL server's STATISTICS objects;
- I plan to add a generic feature (probably a Dictionary<string, object>) for "db specific attributes"; the comparer would then get some string API to select which of this attributes should also be compared.

Questions: Are you interested in this development (of course, you can always look in my fork); and do you or anyone else here have ideas and/or already implementations of such additions?

Harald M.

**Comment by martinjw** [comment]
Yes, I'm interested!

The library is deliberately database agnostic, but while a specific feature like SqlServer Statistics doesn't fit, I would like to add better extensibility so database specific things can be added. I haven't thought much about it, but if you work out a good way, I'll be happy to pull it in.

Keep me updated on your fork.

**Comment by hmmueller** [comment]
Hi Martin, all - 

I have now added Support for "additional properties" in my fork. At the end of the README, I have added some comments on philosopy, API, and design considerations - see https://github.com/hmmueller/dbschemareader#extensions-by-hmmueller

Harald M.

**Comment by martinjw** [comment]
Thanks Harald. Looks good. 

I'll be pushing a new nuget version in a day or so, and after that I'll look into this

**Comment by martinjw** [comment]
I published a new branch with a spike I did over Christmas: https://github.com/martinjw/dbschemareader/tree/Extenders

It think the best way to allow extra information about a database is allow the model to be subclassed. So we have a SqlServerTable which inherits from DatabaseTable. The easiest way to add the necessary extensions is to inherit from DatabaseReader, which has protected methods which can be used:

- AddSchemaFactory(SchemaFactory) : a simple factory so we can subclass DatabaseTable. 
- AddTableExtender(IExtendTable) : inject custom ADO logic for a specific table
- AddSchemaExtender(IExtendSchema) : inject custom ADO logic for the entire schema

IExtendSchema and IExtendTable are pretty simple- you can use whatever ADO style you like:
` void Execute(DatabaseSchema databaseSchema, DbConnection connection);`

You have a cast the databaseSchema or databaseTable so you can get at the subclasses you injected using AddSchemaFactory.

You can also subclass the schema. We already have a way of adding a schema into the DatabaseReader via a constructor...
`        public SqlServerDatabaseReader(string connectionString)   : base(new SqlServerSchema(connectionString))`

I'm including a worked example of a SqlServer extended DatabaseReader here:
https://github.com/martinjw/dbschemareader/tree/Extenders/DatabaseSchemaReader/Extenders/SqlServer

It includes your statistics code (StatisticsReader), and a memory optimised table flag (HekatonReader) which was my own business requirement. As you can see, you can quickly add (and combine) additional readers that are executed by the IExtendSchema and/or IExtendTable. 

For the moment, it's schema or table. Adding more extension points (column, stored procedure...) is possible, but makes customisations potentially more complex. 

Opinions?

**Comment by hmmueller** [comment]
I'll try to look into it in the next days!

(Right now, we are eager and busy to add my current fork Version to our project, because the timeframe for out Redgate license is running out ... I did some things there that probably do not match your philosophy, but "that's my problem" right now; I'll write up my experiences and decisions then for discussion).
