### ISSUE TITLE
MySql Owner

### ISSUE THREAD

**Issue by samcov** [martinjw/dbschemareader#24]
The MySql example requires an owner.

How do you determine the owner? The database I'm using has never required me to have an owner to access it, and I'm not sure if it's the user in the connection string or something else.

**Comment by martinjw** [comment]
The concepts of owner and schema vary over different databases- for MySql it means schema, which is a synonym of database ("Show Databases" or "Show Schema" commands). Each MySql instance can have several databases, including the Information_Schema database. 

Normally you only want to read one specific database. The database should be in the MySql connection string ("Server=localhost;Uid=root;Pwd=xxxx;Database=sakila;"), but other databases are also readable, so set the databaseReader Owner to the database name .

**Comment by samcov** [comment]
Thanks, that cleared that up.

BTW, I'm so glad I found this project. It especially helps me out with .Net Core... Good job!
