### ISSUE TITLE
Oracle EF Provider

### ISSUE THREAD

**Issue by MachineCognitis** [martinjw/dbschemareader#25]
Hi Martin,

The PocoEntityCodeFirst classes generated from an Oracle database have some issues when we try to use them with the Oracle Entity Framework Provider. For example, a NUMBER(2) column is mapped to the decimal type in .NET, but the Oracle EF Provider fails on this mapping; it seems that it requires an Int16, as specified in this [link](http://oradb-srv.wlv.ac.uk/E50529_01/ODPNT/featLINQ.htm).

Is it possible to get the generated classes to work with Oracle EF Provider or is it that we have to use the Devart EF Provider for Oracle?

Thanks,

Robert

**Comment by martinjw** [comment]
I've been testing this against devart and oracle managed client, and so far the latest commit above is working against both, as well as good old (not quite dead yet) System.Data,OracleClient

**Comment by MachineCognitis** [comment]
Thank you! I will check it out.
