### ISSUE TITLE
Must declare the scalar variable "@tableName" Exception

### ISSUE THREAD

**Issue by IAmShipy** [martinjw/dbschemareader#36]
The above error is thrown when reading tables, this is because the parameter name seems to be case sensitive.  

Within `ComputedColumns` class you declare `@tableName` parameter within the Sql, but then add `@TableName` parameter within the `AddParameters` method.

**Comment by martinjw** [comment]
Maybe a collation issue, doesn't affect my databases?

**Comment by IAmShipy** [comment]
Maybe, but it is an issue that breaks your library under certain circumstances, in fact it's unusable!  To be honest, it's the first time I've run into this problem :-(

Thank you for committing the change :-)

**Comment by martinjw** [comment]
I've made the pre-release public: https://github.com/martinjw/dbschemareader/releases/tag/2.3.2.1
I looked through the SQL manually, everything else seems to match case, but let me know if you find any other problems.
I'll push it to a full release in a week or so, depending on what else turns up.
