### ISSUE TITLE
Bulk Insert & Change notification

### ISSUE THREAD

**Issue by weedkiller** [martinjw/dbschemareader#37]
Hi, very nice component 👍 

1. Also, since all/many the parts for the schema/ddl/and compare exist. I am attempting a compare and migrate, would it be possible to get a` bulk insert `or help me get started.
2. [Change notification](https://msdn.microsoft.com/en-us/library/t9x04ed2(v=vs.110).aspx): this plays well with [signalR](https://www.codeproject.com/Articles/883702/Real-Time-Notifications-using-SignalR-and-SQL-Depe), and I was trying to bind the change notifier form the DAL generated here, [any way to turn that on? ](http://www.michalsporek.com/blog/index.php/posts/change-notifications-from-sql-server)

Thanks

**Comment by martinjw** [comment]
1. Presumably you want to replace the Data.InsertWriter, which writes individual insert statements, with something that writes bulk insert. It's not integrated with the compare/migrate code (which is schema only, not data). It's not complex code. bulk insert or bcp are Sql-Server specific, and this library is trying to be database agnostic, but there is a branch to add extensibility points and custom SqlServer stuff. 

2. That would require more extensibility points in the codegen. Again, change notification is sql server specific, so if we add it, it would be in a SqlServer specific version. I'll keep it in mind, but it there's a lot to think about.
