### ISSUE TITLE
Incorrect mapping of PostgreSQL type 'int2'

### ISSUE THREAD

**Issue by jansivans** [martinjw/dbschemareader#38]
You can see in the screenshot inspection of some column received using dbschemareader:
![image](https://cloud.githubusercontent.com/assets/5667073/26715761/8f10e69c-477f-11e7-96dc-f2621a95b430.png)
Type of the column is 'smallint' or 'int2'.
In 'DataType' field you can see that it is mapped to 'Int32' type.
But instead of 'Int32' it should be mapped to 'Int16' as described here: http://www.npgsql.org/doc/types/basic.html

**Comment by jansivans** [comment]
@martinjw Can you also do a release please?

**Comment by martinjw** [comment]
@jansivans Will do very shortly, today if I can, or tomorrow.

**Comment by martinjw** [comment]
@jansivans Pushed new version.

**Comment by jansivans** [comment]
@martinjw Thanks a lot!
