### ISSUE TITLE
oracle How can I set it as int32

### ISSUE THREAD

**Issue by hlm750908** [martinjw/dbschemareader#40]
hello!
  I come from China.
  my db is oracle
  I want the DataType.NetDataTypeCSharpName  to be int32
How do I design field types and lengths?
my email  kw88@qqcom
I await your reply.
Thank you very much for your work

**Comment by hlm750908** [comment]
DbType.Int32, "NUMBER(9)

tks

**Comment by martinjw** [comment]
In Oracle, an integer will probably be represented by NUMBER(10,0)

We map the type "NUMBER" to an equivalent .net type, which is "decimal" (defined in the DataTypeList per database). But the number has a precision and scale, so it's not precise.

In the DataType class we have special logic (NetNameForIntegers) which checks the scale and precision, and assigns it to short/int/long as applicable (returned as a string).  It's accessed by passing the column into the datatype: var str = column.DataType,NetCodeName(column)

Hope this helps
