### ISSUE TITLE
Performance lack retrieving table information of large database

### ISSUE THREAD

**Issue by thomasjoscht** [martinjw/dbschemareader#47]
Hey Guys, I have a simple use case loading table information including table names, column names and data types of one database. One of my target databases is a PostgreSql with 900+ tables and 10k+ columns. I've tried:
- Load information with DatabaseReader.ReadAll() without owner. This will take 3 minutes and more.
- Load information with DatabaseReader.ReadAll() with owner. This will take up to 1 minute.
- Load information with DatabaseReader.AllTables(). This will take up to 1 minute
- Extending lib with custom method: Mainly based on ReaderAdapter.Tables(null), ReaderAdapater.Columns(null) and DatabaseReader.DataTypes(). This will take only few (3 - 5) seconds!

Does a general peformance lack exist in large databases? Have you any other suggestion for retrieving my necessary information? I could create a pull request if no other solution exists.

**Comment by martinjw** [comment]
Yes, performance will be bad on large databases, We're loading a lot of different things under the covers - primary keys, foreign keys, indexes - which is a lot of work. 

There's an incremental technique mentioned here: https://github.com/martinjw/dbschemareader/wiki/More-schema-reading#reading-incrementally
The DatabaseReader.TableList() is just reading the table names, so that's really quick. In the document, I'm loading the columns, constraints and indexes table by table, which will be slow for you (it works really well in a UI when the user manually drills down). If you just use the internal ReaderAdapter to get columns, you won't have constraints- so no primary keys etc. So, yes, table names and columns are pretty quick, but when you want more information, the time starts to add up. I think I'd want at least pks and foreign keys for a minimal but quick read. What do you think?

**Comment by thomasjoscht** [comment]
I'v done a little deeper investigation on my test database on postrgesql. The following results could be a hint for time consumption but is not representative in all circumstances. My database consists of:
- 948 Tables (1111 without owner)
- 9173 Columns (10717 without owner)
- 0 IdentityColumns
- 3621 CheckConstraints
- 943 PrimaryKeys
- 0 UniqueKeys
- 1834 ForeignKeys
- 0 DefaultConstraints
- 0 Triggers
- 738 TableDescriptions
- 845 ColumnDecscriptions
- 0 ComputedColumns
- 0 Indexes

I created 4 profiling runs: ReadAll, ReadAll with owner, AllTables, AllTables with owner. Here are the results for ReadAll:
- **ReadAll**
-- All Users: 0s
-- All Tables: 150s
-- All Views: 0s
-- All SPs: 0s
-- All Seqs: 0s
-- Update Refs: 1s

- **ReadAll with owner**
-- All Users: 0s
-- All Tables: 53s
-- All Views: 0s
-- All SPs: 0s
-- All Seqs: 0s
-- Update Refs: 0s

We see that time consuming is nearly only All Tables. Therefore all other could be ignored. Differences with owner is also big, which is clearly.

Next step is to analyze AllTables which will lead me to the following results:
- **AllTables**
-- Get Tables: 0s
-- Get Columns: 3s
-- Get IdentityColumns: 0s
-- Get CheckConstraints: 1s
-- Get PrimaryKeys: 28s
-- Get UniqueKeys: 0s
-- Get ForeignKeys: 60s
-- Get DefaultConstraints: 0s
-- Get Triggers: 0s
-- Get TableDescriptions: 0s
-- Get ColumnDescriptions: 1s
-- Get ComputedColumns: 0s
-- MergeIndexColumns: 0s
-- Update DataTable objects: 45s

- **AllTables with owner**
-- Get Tables: 0s
-- Get Columns: 2,5s
-- Get IdentityColumns: 0s
-- Get CheckConstraints: 1s
-- Get PrimaryKeys: 2s
-- Get UniqueKeys: 0s
-- Get ForeignKeys: 10s
-- Get DefaultConstraints: 0s
-- Get Triggers: 0s
-- Get TableDescriptions: 0s
-- Get ColumnDescriptions: 1s
-- Get ComputedColumns: 0s
-- MergeIndexColumns: 0s
-- Update DataTable objects: 40s

In my case exists 2 parts which consumes nearly all time: Determine PK's+FK's and update all DataTable objects in foreach (in TableBuilder.Execute()).

- **Update DataTable objects**
-- Update Columns: 0,5s
-- Update Identities: 0s
-- Update CheckConstraints: 0s
-- Update Computed: 0s
-- Update Constraints: 0s
-- Merge Indexes: 40s
-- Update Indexes: 0s
-- Update Triggers: 0s
-- Update Descriptions: 0s
-- Post Processing: 0s

In update DataTable objects the merge index processing which reads indexes per table with ReaderAdapter.Indexes(...) takes long time.

**In the end: I must eliminate PK's+FK's part and computing indexes because I don't need full conditioned informations.**

My suggestion will contain 2 steps: 
First a new method ReadSchema() (or overload of ReadAll) with ReadSchemaOptions parameter. In ReadSchemaOptions every computing part could be turned on and off like
- AllUsers=false 
- AllTables=true
- AllViews=false
- AllStoredProcedures=false
- AllSequences=false
- ReadTableOptions = new ReadTableOptions();

Second a new overload for TableBuilder.Execute with ReadTableOptions parameter. In ReadTableOptions could also each part turned on and off like
[- ReadTables=true]
- Columns=true
- IdentityColumns=false
- CheckConstraints=false
- PrimaryKeys=false
- UniqueKeys=false
- ForeignKeys=false
- DefaultConstraints=false
- Triggers=false
- TableDescriptions=false
- ColumnDescriptions=false
- TableDescriptions=false
- ComputedColumns=false
- Indexes=false

**Comment by thomasjoscht** [comment]
My suggestion will contain 2 steps: 

1. First a new method ReadSchema() (or overload of ReadAll) with ReadSchemaOptions parameter. In ReadSchemaOptions every computing part could be turned on and off like
- AllUsers=false 
- AllTables=true
- AllViews=false
- AllStoredProcedures=false
- AllSequences=false
- ReadTableOptions = new ReadTableOptions();

2. Second a new overload for TableBuilder.Execute with ReadTableOptions parameter. In ReadTableOptions could also each part turned on and off like
- [ReadTables=true]
- Columns=true
- IdentityColumns=false
- CheckConstraints=false
- PrimaryKeys=false
- UniqueKeys=false
- ForeignKeys=false
- DefaultConstraints=false
- Triggers=false
- TableDescriptions=false
- ColumnDescriptions=false
- TableDescriptions=false
- ComputedColumns=false
- Indexes=false

An alternative to my suggestion could be to determine all things out of lib. But therefore a deep knowledge of processing must be exist + necessary information must be available during public methods.

**Comment by martinjw** [comment]
Solution 1, with loads of options, seems like overkill. 
Solution 2, TablesAndColumnsOnly, is fine for your scenario. 
Solution 3, exposing internals, would make a larger, more complicated API surface.

If you want to put solution 2 into a PR, I'll take it.

**Comment by thomasjoscht** [comment]
Ok. I've created a PR for this. New method named "TablesQuickView".

PS: Currently my Visual Studio 2017 Enterprise Version 15.3.4 is crashing opening project DatabaseSchemaReader.csproj. It seems there is a problem with multi framework targeting. I'm not alone with this problem: [see here](https://developercommunity.visualstudio.com/content/problem/117440/crash-when-loading-solution-from-git-repo.html)
Change <TargetFrameworks> property to only one (no matter which one) solves the problem temporarily.
