### ISSUE TITLE
Length of PostgreSql ARRAY data types

### ISSUE THREAD

**Issue by thomasjoscht** [martinjw/dbschemareader#48]
I'm trying to determine the length of ARRAY data types like "character(30)[]" or "character varying(30)[]" in postgresql. The field character_maximum_length is for this fields NULL. After my investigation this should be not possible with information_schema. The only script I found is following:
```sql
SELECT col_attr.attname AS "ColumnName" 
   ,pg_catalog.format_type(col_attr.atttypid, col_attr.atttypmod) AS "DataType"
FROM pg_catalog.pg_attribute col_attr
WHERE col_attr.attnum > 0 AND NOT col_attr.attisdropped AND col_attr.attrelid = (
   SELECT cls.oid
   FROM pg_catalog.pg_class cls
   LEFT JOIN pg_catalog.pg_namespace ns ON ns.oid = cls.relnamespace
   WHERE cls.relname = 'aa');
```

Could you confirm that this isn't possible only using information_schema? Have you any suggestion to solve this "easily" with an extension of lib?

**Comment by martinjw** [comment]
information_schema can be quite limited - it's an ANSI standard, and array datatypes are a PostgreSql specific. 
You should be able to modify DSR to get the data- change the PostgreSql Columns class and sql: https://github.com/martinjw/dbschemareader/blob/master/DatabaseSchemaReader/ProviderSchemaReaders/Databases/PostgreSql/Columns.cs

**Comment by thomasjoscht** [comment]
Ok, thanks! I will initially ignore this. In case this will lead to problem in future I will adjust Sql in Columns class for my purpose in a fork.
