### ISSUE TITLE
PostgreSQL view columns always nullable

### ISSUE THREAD

**Issue by Ravenheart** [martinjw/dbschemareader#5]
When reading a PostgreSQL database schema the returned view columns are marked as nullable always, even if the source table has them set to NOT NULL.

Otherwise this is a fantastic lib!

**Comment by martinjw** [comment]
The view columns are coming directly from the underlying provider- and Npgsql and Devart both always return "nullable". 
So I tried the PostgreSql metadata directly:
```sql
select c.is_nullable from information_schema.columns c
where c.table_name = 'actor_info'
and c.column_name = 'actor_id'
```
Opps, it returns "YES" (that's the primary key of a table via a view, so of course it's not nullable really).

So I don't think I can get the true nullability for views- looks like a fundamental limitation of PostgreSQL metadata. Sorry :disappointed:

**Comment by martinjw** [comment]
Closing as there's nothing we can do about this.
