### ISSUE TITLE
SQL-Server - index columns order issue

### ISSUE THREAD

**Issue by xverwaerde** [martinjw/dbschemareader#51]
SQL-Server - The retrieved columns's order seems to be incorrect - as a consequence, schema comparison often fail and causes index DROP/Re-CREATE.

May I suggest to perform a change in "DatabaseSchemaReader.ProviderSchemaReaders.Databases.SqlServer.Indexes" constructor:

change "ORDER BY  t.name, ind.name, col.name" by "ORDER BY t.name, ind.name, ic.index_column_id"

Thanks, 

Xavier

**Comment by martinjw** [comment]
Thanks, done!
