### ISSUE TITLE
Add the option to specify Command Timeout

### ISSUE THREAD

**Issue by gkathire** [martinjw/dbschemareader#53]
When using the library in a very big DB with thousands of tables and procedures, I'm getting timeout when doing a read all. Please add the ability to specify the Command Timeout option so that we have the ability to tweak as per the size of the DB.

**Comment by martinjw** [comment]
ReadAll() is not recommended for very large databases. Apart from large slow queries, you will eventually hit memory problems. 

There's a way to read incrementally: https://github.com/martinjw/dbschemareader/wiki/More-schema-reading#reading-incrementally

There's also a new method to do a lightweight load coming in the next version.

I'll have a look at what I can do to set a standard timeout.
