### ISSUE TITLE
Change database name for connection; Read existing databases

### ISSUE THREAD

**Issue by thomasjoscht** [martinjw/dbschemareader#54]
Hi,

I'm struggling a little bit with the database name. I need to set it for a connection at runtime without adjusting connection string (because it is unknown/encrypted), f.e. after creation of a new database.

Currently set the database name for connection is only possible in connection string. In Ado the DbConnection method ChangeDatabase will be very useful. But I see no chance to come to this. The connection is normally created via Factory.CreateConnection and used in a using block, f.e. reading schema. There is no way to change database name in this methods.

My second request is to read all databases existing. I think this is also not possible because it will require specific db provider information.

Have you any suggestions?

Thx Thomas

**Comment by martinjw** [comment]
Up to now, using the DatabaseSchemaReader in the .net Framework, the DbConnection is entirely internal and created by factory.CreateConnection.

As from the next version, you can use the same ctor as .net Core to create the DbConnection externally yourself. Apart from the ctor, everything else is identical. Like this:
``` 
using (var connection = new SqlConnection(connectionString)) //connection string could be encrypted
{
    connection.ChangeDatabase("Northwind"); //now you can use this
    var dr = new DatabaseSchemaReader.DatabaseReader(connection);
    var schema = dr.ReadAll();
    //do something with your schema
}
``` 
Another way, with more control, is to use the ConfigurationBuilder in .net 4.7.1 (released today!). You can intercept the config and change it in code: https://blogs.msdn.microsoft.com/dotnet/2017/09/13/net-framework-4-7-1-asp-net-and-configuration-features/

 For reading database names - it's possible, but yes, we'd have to code for each database provider. It's not applicable for some of them (SQLite), there's sometimes a lot of noise from system databases, especially in Oracle, and there might be more security permissions issues.

**Comment by thomasjoscht** [comment]
Hmm ok, that's a little bit limiting for me. Because of WPF I can not go forward to .NET Core. Inject the DbConnection like your new method will be a nice mechanismn for sure. For full .NET an extension possibility for the create connection algorithmn as Action or something could work.

My connectionstrings are not safed in config. Instead they are encrypted persistet. Therefore ConfigurationBuilder is no help unfortunately.

Do you think an implementation for my need on full .NET will be viable?

**Comment by martinjw** [comment]
The constructor with DbConnection will be available on the full framework - not just core- in the next version. I hope to release that in a week or so.

**Comment by thomasjoscht** [comment]
That will be incredible nice. Thx

**Comment by martinjw** [comment]
Now released.
