### ISSUE TITLE
SQL Server user defined types

### ISSUE THREAD

**Issue by mnusr** [martinjw/dbschemareader#58]
are retrieving user defined types supported?

**Comment by martinjw** [comment]
There is a branch, Extenders, which has a SqlServer extension, reading UDTs, statistics, memory optimized flags... 
https://github.com/martinjw/dbschemareader/blob/Extenders/SqlServer/SqlServerSchemaReader/Extenders/SqlServerSchemaExtender.cs

At some point I'll update this.
