### ISSUE TITLE
SQLITE on Mono

### ISSUE THREAD

**Issue by micuentadecasa** [martinjw/dbschemareader#6]
Hi, I want to use your library, mainly with SQLITE in Mono (OS X) but I don't know what provider to use, can u give me some clue? 
I saw in your examples you used a library from devart but it seems is not open source.

**Comment by martinjw** [comment]
Mono has a built-in "Mono.Data.SQLite" provider, which is closely related to the System.Data.SQLite provider from Windows. http://www.mono-project.com/docs/database-access/providers/sqlite/

**Comment by micuentadecasa** [comment]
Hi, you are right, it worked; but It seems it can not get the column.datatype information neither column.iskey for example. I've seen another issue about this that was solved calling dbreader.DataTypes() function, but it doesn't worked for me.

**Comment by martinjw** [comment]
Just tried on Mono. This works fine:
```c#
var cs = "uri=file:northwind.db";

//register Mono.Data.Sqlite so we can refer to it
var factory = new Mono.Data.Sqlite.SqliteFactory ();
DatabaseSchemaReader.Utilities.FactoryTools.AddFactory(factory);

var dsr = new DatabaseReader (cs, "Mono.Data.Sqlite");
var schema = dsr.ReadAll ();

var categories = schema.FindTableByName("Categories");
var id = categories.FindColumn ("CategoryID");

Console.WriteLine (id.IsPrimaryKey); //true
Console.WriteLine (id.DataType); //integer/System.Int64
Console.WriteLine (id.DbDataType); //integer
```

**Comment by micuentadecasa** [comment]
Hi @martinjw , I have tested your solution with my database and I've found that:
- given: I create a table with a field that is primary key, unique and auto increment
- after using schema.FindTableByName... and categories.FindColumn (....)
- in the schema of the table I got two indexes, for example it appears the primary key as an index, but the property PrimaryKey is empty
- I got another index in the table related to the field that is auto increment
- in the field I got nothing about primary keys neither unique property neither data type, but I got autoIncrement values

**Comment by martinjw** [comment]
I see this:
```C#
var table = schema.FindTableByName("cars");
var id = table.FindColumn ("Id");

Console.WriteLine (id.IsPrimaryKey); //true
Console.WriteLine (id.IsIndexed); //true
Console.WriteLine (id.IsUniqueKey); //true
Console.WriteLine (id.DbDataType); //"integer"
foreach (var index in table.Indexes) {
	//"sqlite_master_PK_cars" PRIMARY
	//"sqlite_autoindex_cars_1" UNIQUE
	Console.WriteLine (index.Name + " " + index.IndexType);
}
```
This looks ok to me. (I'm using the latest mono  - 4.2).
