### ISSUE TITLE
OraOleDb.Oracle Not Working

### ISSUE THREAD

**Issue by ylax** [martinjw/dbschemareader#60]
Reader.AllTables() results in an "invalid cast" exception when I create the reader using System.Data.OleDb.OleDbConnection with the OraOleDb.Oracle provider.

**Comment by martinjw** [comment]
The OleDb schema reading is weak compared to the others- ODP, Managed, and the old System.Data,Oracle all provide more information. 

This works for me, against my local db
```C#
const string providername = "System.Data.OleDb";
const string connectionString = "Provider=msdaora;Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SID=XE)));User Id=xxxxx;Password=xxx;";
var dbReader = new DatabaseReader(connectionString, providername);
dbReader.Owner = "AAA";
var tables = dbReader.AllTables();
```
Do you have a stack trace?

**Comment by ylax** [comment]
I don't, sorry. I just switched to Oracle's unmanaged client. Tried using managed client but also encountered an error. If you'd like, I could provide a stack trace for both when I get time. Appreciate your help!
________________________________
