### ISSUE TITLE
Included Non-Key Columns in SQL Server Index

### ISSUE THREAD

**Issue by ylax** [martinjw/dbschemareader#61]
Is there any way to see “included” columns in a SQL Server index? For example, to see “nonKeyCol1” and “nonKeyCol2” in the below example. Also, is there any way to see the “with” options?

CREATE NONCLUSTERED INDEX [idx_myIndex] on [myTable]
(
     [aKeyCol] ASC
) INCLUDE ([nonKeyCol1], [nonKeyCol2]) WITH (Pad_Index = OFF, SORT_IN_TEMPDB = ON) ON “default”

Thanks!
Yl

**Comment by martinjw** [comment]
It does show the "included" columns and this is actually an error! It shows them as normal index columns.  

Included columns are SqlServer specific - there's no equivalent in Oracle for instance (IOTs maybe?) The core part of this library is for common, vanilla databases, but we have a branch called "Extenders" which has SqlServer extensions. This could certainly be added to it.
