### ISSUE TITLE
Unable to access cross schema ForeignKeyChildren for PostgreSQL

### ISSUE THREAD

**Issue by faridmehrhesam** [martinjw/dbschemareader#62]
Table A of Schema A has a foreign key to Table B of Schema B. When I want to access DatabaseTables in ForeignKeyChildren of Table B it is empty.
When I use SQL Server it is OK and works great.

**Comment by martinjw** [comment]
Found the problem- the foreign key query doesn't find the schema of the referenced table.

Fix coming soon.

**Comment by faridmehrhesam** [comment]
Thanks for fixing.
When will this bug fix be available in NuGet package?

**Comment by faridmehrhesam** [comment]
Thanks for fixing.
When will this bug fix be available in NuGet package?

**Comment by martinjw** [comment]
Should be next week. I'm working on something that may or may not be ready in time, but whichever I will make the new nuget package by the middle of next week.

**Comment by faridmehrhesam** [comment]
Thank you
