### ISSUE TITLE
Database first code generation

### ISSUE THREAD

**Issue by PhenX** [martinjw/dbschemareader#63]
Hi, I think this project is what I've been looking for a long time now :)

First, sorry if my question is silly, but I would like to know if there is a plan to support database first code generation to generate DbContext code, because that's how we do for now : 
 * all with EF Core 2.0
 * make changes to the DB schema an SQL Server (or Oracle)
 * generate code with Devart Entity Developer (which is great ! but expensive), it writes the DbContext and all
 * write Liquibase migrations (a lot by hand, some generated with the diff tool embedded with Liquibase)

I'll probably make an issue about Liquibase script generation, if that's necessary.

**Comment by martinjw** [comment]
The existing code generation writes classes and DbContext for EF 6: 
https://github.com/martinjw/dbschemareader/wiki/EF-Code-First

The bulk of this should work for EF Core, but the DbContext and the mapping has some differences. Making it work with EF Core 2 shouldn't be too hard...

**Comment by PhenX** [comment]
Thank you, I discovered this part of the project, and it's seems to work pretty well.
Now I'd like to add more options like : 
* pluralization
* the way files are split
* choose which tables/views/columns to generate
* code templates (T4 ?)

**Comment by martinjw** [comment]
For pluralization, there is an existing setting you can use, and a built-in class called PluralizingNamer. 
```C#
var codeWriterSettings = new CodeWriterSettings
{
	CodeTarget = CodeTarget.PocoEfCore, 
	Namer = new PluralizingNamer()
};
var target = new CodeWriter(schema, codeWriterSettings);
target.Execute(new DirectoryInfo("c:\\Temp\\test"));
```

You can make your own by inheriting from DatabaseSchemaReader.CodeGen.Namer, and overridding NameCollection
```C#
public class MsPluralizingNamer : PluralizingNamer
{
	public override string NameCollection(string className)
	{
		var service =
			System.Data.Entity.Design.PluralizationServices.PluralizationService.CreateService(
				CultureInfo.GetCultureInfo("en-us"));
		return service.Pluralize(className);
	}
}
```

A custom Namer class is also useful for getting rid of database prefixes that some DBAs insist on (override string Name(INamedObject namedObject)).

This works by calling a method ``PrepareSchemaNames.Prepare(schema, codeWriterSettings.Namer)`` which sets the NetName property of tables, views and columns. You can set the NetName directly for better customization- the Prepare method won't overwrite existing NetNames. 

For choosing tables and columns, you need some sort of UI- winforms, asp or some sort of configuration system. Whichever you use, the easiest way prepare the schema is simply remove the tables and columns you don't want, before calling the CodeWriter. If you want more control, and you want to organize how the files are written, you have to write your own CodeWriter and call the underlying writers. At the most simple, it will look like this:
```C#
foreach (var table in schema.Tables)
{
	var cw = new ClassWriter(table, codeWriterSettings);
	string txt = cw.Write();
	WriteFile(txt, table.NetName); //do something with that text
}
```
One of my corporate projects uses T4 templates with this library. The schema provides the NetName properties, flags like IsForeignKey and so on, and for simple requirements it works very well.

Hope this helps!
