### ISSUE TITLE
Connection Name Property

### ISSUE THREAD

**Issue by randerson1001** [martinjw/dbschemareader#64]
I would like to see the addition of a Connection Name property added to the DatabaseSchema class. When dealing with multiple schemas, it would be nice to be able to apply a name. Also, the addition of a ReadOnly property for the connection name in all of the applicable entities (tables, views, storedprocedures, etc.)

[DatabaseSchema Class]
public string ConnectionName { get; set; }

[Entity Property]
public string ConnectionName => DatabaseSchema.ConnectionName;

**Comment by martinjw** [comment]
This is just an arbitrary string, right? 

There's a ConnectionString property already, which can be re-purposed. I've actually done. After I've read a schema, I send the result to a config mgmt system (which must not know the actual connection details for security reasons). I overwrite the connection string with a name ("Northwind")
