### ISSUE TITLE
Reference to object not set for dbreader.table when table has no indexes

### ISSUE THREAD

**Issue by hablaras** [martinjw/dbschemareader#67]
Hi,

The code throws an exception for tables that do not have an index on them.

var fullTable = dbReader.Table("sales"); 

"object reference not set to an instance of an object"

I then added an unique clustered index to the "sales" table and it did not throw the error.

This internal SQL statement returns **no** results when there are no indexes:

  SELECT 
     SchemaName = SCHEMA_NAME(t.schema_id),
     TableName = t.name,
     IndexName = ind.name,
     ColumnName = col.name,
     INDEX_TYPE = ind.type_desc,
     IsPrimary = is_primary_key,
     IsUnique = is_unique_constraint
FROM 
     sys.indexes ind 
INNER JOIN 
     sys.index_columns ic ON  ind.object_id = ic.object_id and ind.index_id = ic.index_id 
INNER JOIN 
     sys.columns col ON ic.object_id = col.object_id and ic.column_id = col.column_id 
INNER JOIN 
     sys.tables t ON ind.object_id = t.object_id 
WHERE 
    (t.name = @TableName OR @TableName IS NULL) AND 
    (SCHEMA_NAME(t.schema_id) = @schemaOwner OR @schemaOwner IS NULL) AND 
	 t.is_ms_shipped = 0 
ORDER BY 
     t.name, ind.name, ic.index_column_id

**Comment by martinjw** [comment]
Do you have the error stack for this? 

The sql statement is finding out the indexes for the table- if there are no indexes on the table, it should return no results, which is correct. There shouldn't be an error here.

**Comment by hablaras** [comment]
Hmm, today I freshly restart VS2017 with the code and now it doesn't throw the error anymore.

I guess you can closed it.

**Comment by martinjw** [comment]
Ok, thanks
