### ISSUE TITLE
Database vendor detection

### ISSUE THREAD

**Issue by dsorokin65** [martinjw/dbschemareader#69]
At th moment you detect the database vendor by analysing of provider name.
But it doesn't work for OleDB and ODBC.
There is a better way to detect the database vendor:

`GetSchema(DbMetaDataCollectionNames.DataSourceInformation)[0]["DataSourceProductName"].ToString()`

It works fine with System.Data.Odbc and System.Data.OleDB.

**Comment by martinjw** [comment]
The vendor detection is used to pick which sql to execute to read the schema. We could check for OleDB, then use this check, and switch to SqlServer or Oracle readers instead.  For ODBC, this won't work as the sql must use positional parameters, not named parameters. 

The built-in OleDb tables are poor, so you'd get better data. On the other hand, you could just use the .net framework providers, unless you have unusually strict corporate rules. So... possible, but not sure if it's worth it...
