### ISSUE TITLE
PostgreSql bpchar data type

### ISSUE THREAD

**Issue by tedypranolo** [martinjw/dbschemareader#7]
Hi Martin,
I am using PostgreSql 9.5 and Npsql 3.0.4.0.
When a column with data type `"char"` , `GetSchema("Columns")` returns `char` for `data_type`. On the other hand a column with data type `character` is returned as `bpchar`.

If I add `bpchar` to `PostgreSqlSchemaReader.SchemaDataTypes`
`list.Add(new DataType("bpchar", typeof(string).FullName));`
It seems to work as expected. I'm new to PostgreSql, but `character` seems like a common data_type, was there a reason this was not part of `PostgreSqlSchemaReader.SchemaDataTypes`?

**Comment by martinjw** [comment]
The Npgsql ADO provider doesn't have any data types information (uniquely - every other database provider has it). So I simply added a list in this library - but I omitted bpchar. 

I've just pushed an update that adds bpchar - pre-release is here: https://github.com/martinjw/dbschemareader/releases/tag/1.4.4.0

**Comment by tedypranolo** [comment]
Thank you Martin. Now I can just use the nuget version instead of having my own fork in my solution.
