### ISSUE TITLE
Oracle's "TIMESTAMP WITH TIME ZONE" should map to System.DateTimeOffset ?

### ISSUE THREAD

**Issue by nunoleong** [martinjw/dbschemareader#70]
Hi Martin,

First of all, excellent work. 

The Oracle data type "TIMESTAMP WITH TIME ZONE" is currently mapping to System.DateTime, but according to the Oracle's mapping documentation [here](https://docs.oracle.com/html/E41125_02/featLINQ.htm) and [here](https://docs.oracle.com/database/121/ODPNT/entityEDMmapping.htm#ODPNT8275) it should map to System.DateTimeOffset.

I've tracked the mapping to the class DatabaseSchemaReader.ProviderSchemaReaders.Databases.Oracle.DataTypeList:

```dts.Add(new DataType("TIMESTAMP WITH LOCAL TIME ZONE", "System.DateTime") {
	ProviderDbType = 19,
	CreateFormat = "TIMESTAMP({0} WITH LOCAL TIME ZONE)",
	LiteralPrefix = "TO_TIMESTAMP_TZ('",
	LiteralSuffix = "','YYYY-MM-DD HH24:MI:SS.FF')",
```
Is this intentional ?

Best,
Nuno

**Comment by martinjw** [comment]
Yes, got that wrong...! Thanks
