### ISSUE TITLE
Oracle's NUMBER mapping is not working correctly

### ISSUE THREAD

**Issue by nunoleong** [martinjw/dbschemareader#71]
Consider the following Oracle table:
```
create table type_numint_table (
number1col          number(1),
number1col2         number(1,0),
number4col          number(4),
number4col2         number(4,0),
number5col          number(5),
number5col2         number(5,0),
number10col         number(10),
number10col2        number(10,0),
number11col         number(11),
number11col2        number(11,0),
number19col         number(19),
number19col2        number(19,0),
number20col         number(20),
number20col2        number(20,0)
);
```

After running `var schema = dbReader.ReadAll();` we get:

`schema.Tables.FirstOrDefault(t=> t.Name == "TYPE_NUMINT_TABLE").Columns.Select(c=> new {c.Name, c.DbDataType, c.Precision, c.Scale, c.DataType}).ToList()`

```
{{ Name = NUMBER1COL, DbDataType = NUMBER, Precision = 1, Scale = 0, DataType = NUMBER = System.Decimal }}
{{ Name = NUMBER1COL2, DbDataType = NUMBER, Precision = 1, Scale = 0, DataType = NUMBER = System.Decimal }}	
{{ Name = NUMBER4COL, DbDataType = NUMBER, Precision = 4, Scale = 0, DataType = NUMBER = System.Decimal }}	
{{ Name = NUMBER4COL2, DbDataType = NUMBER, Precision = 4, Scale = 0, DataType = NUMBER = System.Decimal }}	
{{ Name = NUMBER5COL, DbDataType = NUMBER, Precision = 5, Scale = 0, DataType = NUMBER = System.Decimal }}	
{{ Name = NUMBER5COL2, DbDataType = NUMBER, Precision = 5, Scale = 0, DataType = NUMBER = System.Decimal }}	
{{ Name = NUMBER10COL, DbDataType = NUMBER, Precision = 10, Scale = 0, DataType = NUMBER = System.Decimal }}	
{{ Name = NUMBER10COL2, DbDataType = NUMBER, Precision = 10, Scale = 0, DataType = NUMBER = System.Decimal }}	
{{ Name = NUMBER11COL, DbDataType = NUMBER, Precision = 11, Scale = 0, DataType = NUMBER = System.Decimal }}	
{{ Name = NUMBER11COL2, DbDataType = NUMBER, Precision = 11, Scale = 0, DataType = NUMBER = System.Decimal }}	
{{ Name = NUMBER19COL, DbDataType = NUMBER, Precision = 19, Scale = 0, DataType = NUMBER = System.Decimal }}	
{{ Name = NUMBER19COL2, DbDataType = NUMBER, Precision = 19, Scale = 0, DataType = NUMBER = System.Decimal }}	
{{ Name = NUMBER20COL, DbDataType = NUMBER, Precision = 20, Scale = 0, DataType = NUMBER = System.Decimal }}	
{{ Name = NUMBER20COL2, DbDataType = NUMBER, Precision = 20, Scale = 0, DataType = NUMBER = System.Decimal }}
```
These should map to a variety of _short_, _int_, _long_ and _decimal_ C# types.

From what I could gather, the above is the result of the DatabaseSchemaFixer.FindDataType() method. It is not correctly taking into the account the precision and scale associated with the data type. Fundamentally, the DataType class isn't entirely correct as it expresses a one-to-one mapping through it's properties "TypeName" and "NetDataType".

I did find some code, which seems to be used only under the CodeGen namespace, which would correctly map this at DataType.NetNameForIntegers().

I could do something like this: 
```schema.Tables.FirstOrDefault(t=> t.Name == "TYPE_NUMINT_TABLE").Columns.FirstOrDefault(c => c.Name == "NUMBER4COL").DataType.NetCodeName(schema.Tables.FirstOrDefault(t=> t.Name == "TYPE_NUMINT_TABLE").Columns.FirstOrDefault(c => c.Name == "NUMBER4COL"))```

which would return the string "short" and then get a System.Type from there, but I find two problems with this:
- it looks unnecessary complicated;
- in terms of "correctness", the DataType instance of the Column should directly return the correct type

Proposal:
- Option 1 (simpler): Method DatabaseSchemaFixed.FindDataType()'s signature could be changed to add additional arguments: precision and scale. 
- Option 2 (more complicated): The DataType class could be refactored to support many-to-one mappings.

I could do a pull request for Option 1, if you agree. Option 2 would require a bit more thinking :)

**Comment by martinjw** [comment]
Yes, Oracle puts all number types into NUMBER while other databases tend to have an alias for INT etc, which makes them easier to map. From column you can call column.DataType.NetDataType or NetDataTypeCSharpName, but on Oracle NUMBERs these are misleading. 

So- here's my simple "option 3"...

An extension method of DatabaseColumn (so you have all the properties)- eg column.NetDataType() - , which basically does what DataType.NetCodeName(col) does.

You could add more DataTypes for int, short, etc, but the Fixer.FindDataType() logic becomes more complex and it's already pretty slow for large databases, when it's doing thousands of columns and arguments.

**Comment by nunoleong** [comment]
Good point on performance impact. I'll try and run a dotTrace to have a peek on the call stats.

I did a quick prototype of your suggestion, and sure enough, it looks much better:

```
{{ Name = NUMBER1COL, DbDataType = NUMBER, Precision = 1, Scale = 0, NetDataType = System.Decimal }}
{{ Name = NUMBER1COL2, DbDataType = NUMBER, Precision = 1, Scale = 0, NetDataType = System.Decimal }}
{{ Name = NUMBER4COL, DbDataType = NUMBER, Precision = 4, Scale = 0, NetDataType = System.Int16 }}
{{ Name = NUMBER4COL2, DbDataType = NUMBER, Precision = 4, Scale = 0, NetDataType = System.Int16 }}	
{{ Name = NUMBER5COL, DbDataType = NUMBER, Precision = 5, Scale = 0, NetDataType = System.Int32 }}
{{ Name = NUMBER5COL2, DbDataType = NUMBER, Precision = 5, Scale = 0, NetDataType = System.Int32 }}
{{ Name = NUMBER10COL, DbDataType = NUMBER, Precision = 10, Scale = 0, NetDataType = System.Int32 }}
{{ Name = NUMBER10COL2, DbDataType = NUMBER, Precision = 10, Scale = 0, NetDataType = System.Int32 }}
{{ Name = NUMBER11COL, DbDataType = NUMBER, Precision = 11, Scale = 0, NetDataType = System.Int64 }}
{{ Name = NUMBER11COL2, DbDataType = NUMBER, Precision = 11, Scale = 0, NetDataType = System.Int64 }}
{{ Name = NUMBER19COL, DbDataType = NUMBER, Precision = 19, Scale = 0, NetDataType = System.Decimal }}
{{ Name = NUMBER19COL2, DbDataType = NUMBER, Precision = 19, Scale = 0, NetDataType = System.Decimal }}
{{ Name = NUMBER20COL, DbDataType = NUMBER, Precision = 20, Scale = 0, NetDataType = System.Decimal }}	
{{ Name = NUMBER20COL2, DbDataType = NUMBER, Precision = 20, Scale = 0, NetDataType = System.Decimal }}	
```

Code is pretty simple, at DataBaseColumnExtensions.cs:

```
        /// <summary>
        /// Returns the .NET type of the column.
        /// </summary>
        /// <param name="column">The column.</param>
        /// <returns>The .NET type of the column</returns>
        /// <remarks>
        /// For numeric Db data types uses column.Precision and column.Scale to determine the correct .NET data type.
        /// </remarks>
        public static Type NetDataType(this DatabaseColumn column)
        {
            if (column == null) return null;
            if (column.DataType == null) return null;
            
            if (!column.DataType.IsNumeric || column.DataType.IsInt) return column.DataType.GetNetType();
            var precision = column.Precision.GetValueOrDefault();
            var scale = column.Scale.GetValueOrDefault();
            return NetTypeForIntegers(column, scale, precision);
        }


        private static Type NetTypeForIntegers(DatabaseColumn column, int scale, int precision)
        {
            if (scale != 0 || precision >= 19) return column.DataType.GetNetType();

            //could be a short, int or long...
            //VARCHAR2(10) is common for Oracle integers, but it can overflow an int
            //int.MaxValue is 2147483647 so +1 is allowable in the database
            if (precision > 10) //up to long.MaxValue
            {
                return typeof(long);
            }
            if (precision > 4) //2147483647
            {
                return typeof(int);
            }
            if (precision > 1)
            {
                return typeof(short);
            }
            return column.DataType.GetNetType();
        }
```

A couple of notes:
Note 1 - This works, however it does feel a bit strange/hack'ish, from an object model point of view. We have a DataBaseColumn.DataType property which continues to be misleading. We then have a DataBaseColumn.NetDataType() method, which looks fairly redundant with the above property, from an API point of view, and actually is the one that "matters". Perhaps naming it something else, to further differentiate from the DataType property...

Note 2 - The if condition (precision > 1) should actually be (precision > 0), otherwise number(1) will map to System.Decimal ?

Note 3 - The other if condition (precision > 10) is bothering me, although it does match Oracle's [documentation](https://docs.oracle.com/database/121/ODPNT/entityEDMmapping.htm#ODPNT8275). Perhaps I'm misreading something ?
    number(10) is mapping to System.Int32.
    number(10)'s maximum value in the DB is: 9999999999 
    Int32.MaxValue is                                         2147483647

Therefore, if we use this mapping don't we risk overflowing Int32?

Note 4- The if condition (precision > 4) actually mitigates this for Int16. 
According to the same Oracle's docs, number(5) should map to Int16, which would give us a similar overflow scenario.

Best,
Nuno

**Comment by martinjw** [comment]
We are modelling 2 different things here- the database and a .net translation of it.

column.DataType is the model for the database datatype, which is NUMBER. The Oracle data type definition is much wider than the .net equivalent. DataType.NetDataType for Oracle "NUMBER" must be decimal, but the mapping for a column with a specific scale/precision can be more specific.

The precision limits were based on the Oracle docs, modified by experience. As the comment says, NUMBER(10) is very common in Oracle for integers, at least the ones I've used, even though technically there could be a long value.  In most cases, the systems using the databases are using ints, not shorts or longs, so it makes sense to tip the precision limits to favor standard ints.

**Comment by nunoleong** [comment]
Agreed with the modelling reasoning.

As for number(10), well, I guess it's up to the consumer of the metadata to be conscious of this. Personally, if there is a chance of overflowing at .NET, I wouldn't map to Int32. We actually had this happening with a legacy system where a single db sequence was used to generate PK's for all the tables., which broke a couple of apps which mapped to Int32. :)

**Comment by laredoza** [comment]
Hi,
I've implemented the fix from @nunoleong and it works. What is the long term resolution to this issue?
Thanks in advance
