### ISSUE TITLE
the column property DataType is null

### ISSUE THREAD

**Issue by Jabben2015** [martinjw/dbschemareader#75]
i want to use this project to generate database entities,but i found that DatabaseReader.Table method does't return the column's property 'DataType',so i don't know what the column's type infomation,how can i do ?
i just want to generate the specified table entity,so i would not call the ReadAll or AllTables method

**Comment by martinjw** [comment]
Load the datatypes first. Then, when you load the table, the datatypes are automatically set on the columns.

```C#
dbReader.DataTypes();
var table = dbReader.Table("Products");
```

**Comment by Jabben2015** [comment]
Thanks.
