### ISSUE TITLE
"Column "condition_timing" does not exist" error in postgresql 11 beta

### ISSUE THREAD

**Issue by jansivans** [martinjw/dbschemareader#80]
When trying to call `.ReadAll()` method on `DatabaseReader` instance, `column "condition_timing" does not exist` exception is thrown.

Works fine with postgresql 10 and 9, but doesn't work with 11.

**Comment by martinjw** [comment]
PostgreSql 11 is still in beta 2, but I guess this is a problem with version parsing.

I changed the how it gets the server version- pre-release nuget is here https://github.com/martinjw/dbschemareader/releases/tag/2.6.1.1

If you can let me know if this helps, I'll release soon.

**Comment by jansivans** [comment]
Thanks for the help. I've tested with `2.6.1.1` - previous exception gone, but now it throws a new one - `column "proisagg" does not exist`.

**Comment by martinjw** [comment]
Oh great, they changed the pg_proc system catalog for v11- proisagg is now prokind 
https://www.postgresql.org/docs/11/static/catalog-pg-proc.html

Maybe we just skip checking for aggregate functions...

**Comment by martinjw** [comment]
New candidate: https://github.com/martinjw/dbschemareader/releases/tag/2.6.1.4

The rest of the function/procedure catalogs look ok, but there may be something else elsewhere.

Thanks for the feedback!

**Comment by jansivans** [comment]
Works fine. Thank you!
