### ISSUE TITLE
[MSSQL] Should is_unique instead of is_unique_constraint be used for indexes

### ISSUE THREAD

**Issue by tostringtheory** [martinjw/dbschemareader#81]
I am using this package on a personal project and came across an interesting behavior when looking at a table I knew had unique indexes on it - this package reported that the indexes were not unique.  Looking at the source of Indexes.cs for what might be the cause.  I see that the SQL was using is_unique_constraint from the sys.indexes view instead of is_unique.  

I'd do a PR, but wanted to see if this would even be wanted?

**Comment by martinjw** [comment]
Quoting from https://docs.microsoft.com/en-us/sql/relational-databases/indexes/create-unique-indexes?view=sql-server-2017

> There are no significant differences between creating a UNIQUE constraint and creating a unique index that is independent of a constraint.

A unique constraint is implemented as a unique index. Best practice, I think, is to use a constraint as it makes the intent clear. A unique constraint is an ANSI standard logical design, while a unique index is a physical implementation which may not translate to another database. 

We also don't do anything SqlServer specific, like read INCLUDED columns- we're deliberately creating a simple but sufficient model of the database. I am wary of complicating the model by introducing constraint and non-constraint unique indexes, when I think most usage would be constraints. But I'm willing to be persuaded if you think it can be done simply and clearly.

**Comment by tostringtheory** [comment]
Thanks for getting back to me.  I'll elaborate some more - 

At least in my reading, it appears that MSSQL implemented the unique constraint ANSI standard by usage of a unique index that always gets created with a unique constraint - unique indexes may be defined by a unique constraint, but not necessarily.  So the unique constraint clearly defines intent, however is not always used due to a few options that are unavailable during constraint creation, versus direct index creation.

Further reinforcing that last point, I think that many people don't even go to create the unique constraint when they want uniqueness in a table, they just define the unique index.  I can point to a great example of this in how entity framework code first generates unique's when you specify them - just by an index, not a constraint.  That's not to say that EF is always the shining example of perfect SQL code, but it does give some insight into this situation.

Next - I'd like to point out that I am trying to determine via the Indexes property on a DatabaseTable object if that table has any indexes that are unique.  At this point, I don't care about the unique keys - just the indexes which may or may not be defined as a unique constraint.  That was the cause of my original confusion of looking at a table that had 3 unique indexes and seeing none.  In my specific case here - 2 of the indexes were unable to be unique constraints because they were filtered indexes that you can't create as a unique constraint, but you can as a direct unique index.

In summary, even from the article you linked - as well as this one [https://www.mssqltips.com/sqlservertip/4270/difference-between-sql-server-unique-indexes-and-unique-constraints/](https://www.mssqltips.com/sqlservertip/4270/difference-between-sql-server-unique-indexes-and-unique-constraints/):

> Generally there is no functional difference between a unique index and a unique constraint. The latter is also listed as a constraint, however this is only a method to emphasize the purpose of the index. There is no difference for the query optimizer whether the index is created as a unique index or a unique constraint, therefore there is no performance difference. However there are some differences for creation where some index creation options are not available for unique constraints.

Thus, I would say that in the SQL to grab index information from SQL server, that the is_unique_constraint column be changed to instead grab the is_unique column, as that specifies if the index is unique (which is what you show in the object model), NOT the is_unique_constraint (which merely indicates its created as a product of a unique constraint).  I don't believe further work would be needed in the object model besides this to capture/propagate this information.  As well, any unique constraint that was previously shown as IsUnique in the object model would remain untouched, it would just effect showing other unique indexes that were suppressed before.

Is that any clearer, or did I happen to just make what I was saying more confusing?  BTW - great package - I enjoy its feature set so far!

PS - sorry for the lack of information in the first post.  I've been working on trying to find a balance in my descriptions/posts I leave places as I can end up being super verbose - but I feel that I probably missed the mark before.

**Comment by martinjw** [comment]
Ok, after thinking about it... I think I agree with you. If there is a unique constraint, the model has both the constraint and the index (with the same name). If there is just a unique index, the uniqueness isn't visible. 

Can you do the pull request?

**Comment by tostringtheory** [comment]
Submitted PR#82

**Comment by martinjw** [comment]
Merged - thanks! 
Waiting a response on another issue, but I'm planning on publishing the nuget by the end of the week.
