### ISSUE TITLE
Is it possible to change logging verbosity?

### ISSUE THREAD

**Issue by Griswald-911** [martinjw/dbschemareader#83]
First of all, I really appreciate all the work you've done! I am on a project that uses your library to compare schemas between SQL Server databases in order to merge data between them and it makes our life immeasurably easier than before, hands down. 

Anyway, we are in the middle of upgrading our project and migrated from Nuget package version 1.5.0.5 to 2.6.1. When running our project, we noticed that the SQL statements used to gather schema information from the database are now being dumped to the Console. This wasn't the case with the older version. I haven't looked too deeply into the source code, but I was just wondering if there is a way to set verbosity levels on some of this output? Our output gets redirected to a customer-facing module and we would like to keep some of the scary details out of their purview if at all possible :)

Thanks you ahead of time for your time.

**Comment by martinjw** [comment]
The sql logs are being written using a simple trace write. If you can, you can change the filter on your trace listener (above verbose). I presume your trace listener is there to pick up other logs from your application. If you use trace sources, you have more filtering control, but at the moment this library doesn't.

**Comment by Griswald-911** [comment]
@martinjw You are correct. Our trace listener is set up to pick up logs from within our application and various endpoints in the system (trhough SignalR). I wasn't aware of the filter system and am looking into it and trace sources now. I'm hoping there is a way to maybe exclude traces from certain dlls or something. Thanks for the push in the right direction.
