### ISSUE TITLE
SQL Server IMigrationGenerator.RenameTable results in double quoted table.

### ISSUE THREAD

**Issue by groogiam** [martinjw/dbschemareader#86]
The generated migration for sql server IMigrationGenerator.RenameTable appear to double quote tables.
Renaming a table from Project to Companies results in the following sql

`sp_rename '[Project]','[Companies]';`

The resulting change is a double quoted table.

![image](https://user-images.githubusercontent.com/1992395/45466540-7536e580-b6e8-11e8-9760-12d7fbe122c9.png)

It appears that if you are going to use SQL Server Quoting [] then the single quotes are not required. The below sql seems to work as expected.

`sp_rename [Project], [Companies];`

This same issue is probably present other renames as well. E.g. column renames.

**Comment by martinjw** [comment]
Fix in 2.6.3
