### ISSUE TITLE
Only populates the first argument in a postgres function

### ISSUE THREAD

**Issue by oferns** [martinjw/dbschemareader#89]
In a postgres function, I am only getting the first argument of the function in the DatabaseFunction object. I will investigate and post what I find

**Comment by oferns** [comment]
ok so the issue is in DatabaseSchemaReader.ProviderSchemaReaders.Databases.PostgreSql.ProcedureArguments around line 80. I've created a PR. https://github.com/martinjw/dbschemareader/pulls 
Happy to discuss

**Comment by martinjw** [comment]
Merged, thanks! Will push release to nuget at the weekend

**Comment by oferns** [comment]
Ok great! The library is really useful. I use it in combination with Roslyn/SyntaxFactory to generate attributed models to use with dapper and it works a treat so many thanks for your efforts and if I come across any more hiccups I'll do me best!
