### ISSUE TITLE
DB2 Data Types

### ISSUE THREAD

**Issue by Petran15** [martinjw/dbschemareader#9]
Hi All,
Is anyone of you facing issues with datatypes for the columns when we use DB2 Connection string ?

Seems to be fine with tables names and column name, although the data type is not working properlly.

I think that in Db2ISeriesSchemaReader.cs is missing the classes that suppose to return the data types !!

Any idea ??

Thanks in advance

**Comment by martinjw** [comment]
Db2ISeriesSchemaReader relies on the underlying IBM .net ADO provider, which should provide the datatypes. The underlying call is basically this:
```c#
            const string providername = "IBM.Data.DB2";
            const string connectionString = @"Server=localhost:50000;UID=db2admin;pwd=db2;Database=Sample"; //change this!
            var factory = System.Data.Common.DbProviderFactories.GetFactory(providername);
            using (var connection = factory.CreateConnection())
            {
                connection.ConnectionString = connectionString;
                connection.Open(); //requires open connection, but doesn't actually touch database
                var dataTypes= connection.GetSchema(System.Data.Common.DbMetaDataCollectionNames.DataTypes);
                foreach (DataRow row in dataTypes.Rows)
                {
                    foreach (DataColumn col in dataTypes.Columns )
                    {
                        Console.WriteLine(col.ColumnName + " = " + row[col.ColumnName]);
                    }
                }
            }
```
For datatypes, all we do is turn this datatable into a list of simple .net objects, DataType
```c#
            var dbReader = new DatabaseReader(connectionString, providername);
            var types = dbReader.DataTypes();
```
Two things may be going wrong...

- The IBM ADO provider isn't returning the datatypes datatable (the first code sample errors or returns nothing)
- The provider is returning different column names than we expect. Of course, IBM is the only one who does this differently, and we have special coding in SchemaConverter for DB2, but iSeries may be different (thank you, IBM)

I don't have access to iSeries, so I'd be very happy if you could run the first sample and tell me what happens- and what the output is. If the naming is different, it's an easy fix.

**Comment by Petran15** [comment]
Hi,

I couldn't manage to find an easy way to display the metadata from a IBM iSeries db, although I used another approach (SSIS to extract the metadata, which seems to be fine).

I still have the same issue: On the display tree, the metadata column is either empty or DECFLOAT. 

Thanks

**Comment by martinjw** [comment]
According to the IBM.Data.DB2.iSeries.dll version 12.0.0.0, the DataTypes schema collection should include all the values for IBM.Data.DB2.iSeries.iDB2DbType including DECFLOAT16 and DECFLOAT34 (depending on the host version - internally this is done in iDB2Schemas)

It should work, but I've no way of debugging this for you. :disappointed:
