### ISSUE TITLE
Oracle DataTypeWriter  Bug

### ISSUE THREAD

**Issue by AiKier** [martinjw/dbschemareader#91]
In oracle, if Number is not empty and has default values, 'not null' in the 'default value' rear.
`"XXXX" NUMBER(10) NOT NULL DEFAULT 1`  Error；
`"XXXX" NUMBER(10) DEFAULT 1 NOT NULL `  Success；

**Comment by AiKier** [comment]
date type default 
`if (dataType == "DATE")
            {
                sql = "DATE";
                if (!string.IsNullOrEmpty(defaultValue))
                    sql += " DEFAULT DATE '" + defaultValue + "'";
            }`
Created `"XXXX" DATE DEFAULT DATE '(current_timestamp)'` Error；

The method I think of for the time being
`if (!string.IsNullOrEmpty(defaultValue) && defaultValue.Trim() == "(current_timestamp)")
                    sql += " DEFAULT sysdate NOT NULL";`

**Comment by martinjw** [comment]
New version now pushed to nuget

**Comment by AiKier** [comment]
@martinjw 

> if (dataType == "BLOB")
            {
                sql = dataType;
                if (!string.IsNullOrEmpty(defaultValue))
                    sql += " DEFAULT " + AddQuotedDefault(defaultValue);
            }

Your AddQuotedDefault method uses single quotes, but BLOB defaults EMPTY_BLOB() cannot use single quotes.

I amended it to：
> if (dataType == "BLOB")
            {
                sql = dataType;
                //if (!string.IsNullOrEmpty(defaultValue))
                //    sql += " DEFAULT " + AddQuotedDefault(defaultValue);
                if (!string.IsNullOrEmpty(defaultValue))
                    sql += " DEFAULT " + defaultValue;
            }

**Comment by AiKier** [comment]
@martinjw  
The default string you get will have quotes, but I don't know why statements are sometimes generated, and some quotes will wrap lines and add commas.
Example：
>   S VARCHAR2 (200 CHAR),
  STATU VARCHAR2 (20 CHAR) DEFAULT '1
', 
  CODESTATU NUMBER DEFAULT 0,
  CODEDATE DATE,

The middle " ', "  should be on it.

Also：
>   "FINISH_TIME" CHAR (6),
  "RELATION_ID" NUMBER (19),
  "JZ_FLAG" CHAR (1) DEFAULT '0'
,
);

The last " , "should be removed

Besides, I don't understand why varcha2 needs char?
The comparative database VARCHAR2 does not have char
> A VARCHAR2 (4000 CHAR),
B VARCHAR2 (4000 CHAR),
ID NUMBER NOT NULL

When creating an index 
Report Errors：
Exceeding the maximum keyword length (6398) 
After deleting char，No problem.

_I'm sorry, my English is not very good. Many of them are translated by machine._

**Comment by AiKier** [comment]
>  
CREATE TABLE "OA_JGXZ_INFO"
(
 "DJ" VARCHAR2 (50) DEFAULT 'X1',
  "ZJ" VARCHAR2 (50) DEFAULT 'X2'
',
  "ZYZZ" VARCHAR2 (200) DEFAULT 'X3'
'
);

I thought it was because I used the previous version, but when I updated it to the latest version, it still happened.

**Comment by martinjw** [comment]
@AiKier  I found the problem- the data_default in column can sometimes have a new line character at the end. That confuses the formatting. I'll have a fix very shortly.

**Comment by AiKier** [comment]
@martinjw  Thank you. This update has helped me a lot.

**Comment by AiKier** [comment]
@martinjw  
Set up Oracle TIMESTAMP DEFAULT is systimestamp

>   "Test" TIMESTAMP (6) DEFAULT TIMESTAMP 'systimestamp', --Error  You can't. " ' "
  "Test" TIMESTAMP (6) DEFAULT TIMESTAMP systimestamp,  --Error  List is not allowed here
  "Test" TIMESTAMP (6) DEFAULT systimestamp,  --Success

**Comment by martinjw** [comment]
Done a fix for that... see the latest commit
