### ISSUE TITLE
Execution Timeout

### ISSUE THREAD

**Issue by brandonam** [martinjw/dbschemareader#92]
Is there still a chance to get an option to change the standard execution timeout? 

I know it was mentioned in #53 and I'm doing the incremental table reads to try elevate the problem. 

It's working great but I'm using the library on massive legacy MSSQL databases that may be hosted at other sites with hundreds of views/procs. So I occasionally end up with deadlocks/execution timeouts

**Comment by martinjw** [comment]
New version now pushed to nuget
