### ISSUE TITLE
Oracle Bug

### ISSUE THREAD

**Issue by AiKier** [martinjw/dbschemareader#93]
`SELECT OWNER, OBJECT_NAME, PROCEDURE_NAME, OBJECT_TYPE FROM ALL_PROCEDURES WHERE (OWNER = :OWNER OR :OWNER IS NULL) AND (OBJECT_NAME = :NAME OR :NAME IS NULL) AND (OBJECT_TYPE = 'PROCEDURE' OR OBJECT_TYPE = 'PACKAGE') AND NOT (PROCEDURE_NAME IS NULL AND OBJECT_TYPE = 'PACKAGE') AND OWNER NOT IN ('SYS', 'SYSMAN', 'CTXSYS', 'MDSYS', 'OLAPSYS', 'ORDSYS', 'OUTLN', 'WKSYS', 'WMSYS', 'XDB', 'ORDPLUGINS', 'SYSTEM')`
In Oracle 10.2, Report errors：invalid identifier.
In Oracle 10.2, ALL_PROCEDURES has no OBJECT_TYPE field.

In Oracle 11.2, the OBJECT_TYPE field is in ALL_PROCEDURES

**Comment by martinjw** [comment]
An old Oracle version! The fix to ProviderSchemaReaders\Databases\Oracle\StoredProcedures.cs

```C#
            if (Version(connectionAdapter.DbConnection) < 11)
            {
                //In Oracle 10.2, ALL_PROCEDURES has no OBJECT_TYPE field. The OBJECT_TYPE field is in DBA_OBJECTS.
                 Sql = @"SELECT P.OWNER,
  P.OBJECT_NAME,
  P.PROCEDURE_NAME,
  O.OBJECT_TYPE
FROM ALL_PROCEDURES P
INNER JOIN ALL_OBJECTS O ON O.OBJECT_ID = P.OBJECT_ID
WHERE (P.OWNER = :OWNER OR :OWNER IS NULL)
AND (P.OBJECT_NAME = :NAME OR :NAME IS NULL)
AND (O.OBJECT_TYPE = 'PROCEDURE' OR O.OBJECT_TYPE = 'PACKAGE')
AND NOT (P.PROCEDURE_NAME IS NULL AND O.OBJECT_TYPE = 'PACKAGE')
AND P.OWNER NOT IN ('SYS', 'SYSMAN', 'CTXSYS', 'MDSYS', 'OLAPSYS', 'ORDSYS', 'OUTLN', 'WKSYS', 'WMSYS', 'XDB', 'ORDPLUGINS', 'SYSTEM')";
            }
```

**Comment by AiKier** [comment]
In 10.2, there is no OBJECT_ID in ALL_PROCEDURES.

**Comment by AiKier** [comment]
Maybe can try it.
I ran successfully in 10.2.0.1.0
> select 
  P.OWNER, 
  P.OBJECT_NAME, 
  O.OBJECT_TYPE, 
  P.PROCEDURE_NAME
from ALL_PROCEDURES P
  left outer join ALL_OBJECTS O
  on (
    O.OWNER = P.OWNER
    and O.OBJECT_NAME = P.OBJECT_NAME
  )
 where (
(P.OWNER = :OWNER OR :OWNER IS NULL)
AND (P.OBJECT_NAME = :NAME OR :NAME IS NULL)
AND (O.OBJECT_TYPE = 'PROCEDURE' OR O.OBJECT_TYPE = 'PACKAGE')
AND NOT (P.PROCEDURE_NAME IS NULL AND O.OBJECT_TYPE = 'PACKAGE')
AND P.OWNER NOT IN ('SYS', 'SYSMAN', 'CTXSYS', 'MDSYS', 'OLAPSYS', 'ORDSYS', 'OUTLN', 'WKSYS', 'WMSYS', 'XDB', 'ORDPLUGINS', 'SYSTEM')
 )

**Comment by AiKier** [comment]
@martinjw  
If the primary key name is scrambled, it cannot be executed.
Double quotation marks need to be added to the primary key name
> ALTER TABLE Table_Name ADD CONSTRAINT BIN$BQw9CXEuROGAY1quKEtLyA==$0 PRIMARY KEY (ROLE_ID, MENU_ID);     --Report errors
ALTER TABLE Table_Name ADD CONSTRAINT "BIN$BQw9CXEuROGAY1quKEtLyA==$0" PRIMARY KEY (ROLE_ID, MENU_ID);  Success

Although I don't know why the primary key name should be named like this. : (
