### ISSUE TITLE
VistaDB

### ISSUE THREAD

**Issue by safepage** [martinjw/dbschemareader#94]
Hi,

I am looking to implement classes for VistaDbAdapter.cs and Databases\VistaDB\Columns.cs, Tables.cs etc.

I was wondering if you had already looked at this as there are some references in the code to VistaDB, but no implementation of these classes?

**Comment by martinjw** [comment]
I haven't worked with VistaDb for a while, so no, I haven't done any implementation.  The VistaDb stuff uses the DbProviders - see `DatabaseSchemaReader.ProviderSchemaReaders.VistaDbSchemaReader` - which should still work in full .net, but not in core, and slower than the custom database readers.

**Comment by safepage** [comment]
I looked into this a bit more and whilst getting the Table schema info can be done in SQL a similar way to the other readers:
```
Sql = @"SELECT name FROM [database schema]
WHERE typeid = 1 AND (name = @TABLE_NAME or (@TABLE_NAME is null))
ORDER BY name";
```

Getting the Column Schema would require 2 reads from the [database schema] as self joins are not supported, so this doesn't really fit? An alternative is to just use the ADO model in a similar way to the SQLite version:

```
        public IList<DatabaseColumn> Execute(IConnectionAdapter connectionAdapter)
        {
            var tables = new Tables(CommandTimeout, _tableName).Execute(connectionAdapter);

            foreach (var table in tables)
            {
                var tableName = table.Name;
                using (var cmd = connectionAdapter.DbConnection.CreateCommand())
                {
                    cmd.CommandText = $"Select * from [{tableName}]";

                    using (var dr = cmd.ExecuteReader(System.Data.CommandBehavior.SchemaOnly))
                    {
                        System.Data.DataTable schemaTable = dr.GetSchemaTable();

                        foreach (System.Data.DataRow row in schemaTable.Rows)
                        {
                            var col = new DatabaseColumn
                            {
                                Name = row["ColumnName"].ToString(),
                                TableName = tableName,
                                SchemaOwner = "",
                                Ordinal = System.Convert.ToInt32(row["ColumnOrdinal"], CultureInfo.CurrentCulture),
                                DbDataType = row["DataTypeName"].ToString(),
                                Nullable = System.Convert.ToBoolean(row["AllowDBNull"], CultureInfo.CurrentCulture),
                                Precision = System.Convert.ToInt32(row["NumericPrecision"], CultureInfo.CurrentCulture),
                                Scale = System.Convert.ToInt32(row["NumericScale"], CultureInfo.CurrentCulture),
                                DefaultValue = row["DefaultValue"].ToString(),
                                IsPrimaryKey = System.Convert.ToBoolean(row["IsKey"], CultureInfo.CurrentCulture),
                            };
                            Result.Add(col);
                        }
                    }
                }
            }
            return Result;
        }
```

Is this approach OK?

**Comment by safepage** [comment]
Thanks, but I don't see that with the other providers?

Each of them (except SQLite) appear to specify the TableName in the WHERE clause of the Column schema retrieval SQL.

You cannot do that with VistaDB without two lookups on the [database schema] table, i.e. one to get the table id and one to get the Column meta data using the table id in the reference column, as self joins are not supported.

My solution works like the SQLite provider by doing it all in the Execute method.
