### ISSUE TITLE
GetNetType and nullable types

### ISSUE THREAD

**Issue by Sigvaard** [martinjw/dbschemareader#95]
`GetNetType` seems to ignore nullable types and types are always not nullable for columns that allow NULLs. Consider checking if a column is nullable and convert type to nullable type.

**Comment by martinjw** [comment]
`GetNetType` is a method off `DataType`, which is just the raw Sql types (like varchar) with their .net mappings. It doesn't know about nullables, which is a column property. 

So you don't get nullable information from `column.DataType.GetNetType()` and the slightly more intelligent extension method `column.NetDataType()` . 

The `CodeGen` namespace includes `DataTypeWriter` which does the additional processing to return a string of the .net type with correct nullable plus precise numeric types (int, decimal, long, short...)
